### ISSUE TITLE
Red Screen using Crash Bandicoot 3 PAL (SCES-01420 PLATINUM)

### ISSUE THREAD

**Issue by Naitoraven951** [socram8888/tonyhax#10]
I've copied the raw file on the MC using ulaunchelf, I can see the save progress called "TONYHAX" but after loading -- red screen fix.

(Video attached):

SCPH-5502 / PAL / Not modchipped.

https://youtu.be/u1JWqdeWGRI

**Comment by socram8888** [comment]
Did you also copy the second file, the tonyhax SPL?

**Comment by Naitoraven951** [comment]
Hi, thanks for the fast response!
I've downloaded the 1.2 on github, but there is no -- SPL file.

I was sure I do something wrong.

Lemme check...

**Comment by socram8888** [comment]
It's `BESLEM-99999TONYHAX` or `tonyhax.mcs` depending on which installation method you are using.

**Comment by Naitoraven951** [comment]
Yup!
It works :-)!!!

Thanks so much for help and keep going with tonyhax <3 !

**Comment by socram8888** [comment]
Perfect, glad it worked.
