### ISSUE TITLE
Black screen with original game SLES-02532

### ISSUE THREAD

**Issue by santiis2010** [socram8888/tonyhax#102]
Before opening this kind of issue, please ensure:
 - Are you using a compatible console version? Yes
 - Are you using CD-R media, and not CD-RW? CD-R
 - Did you copy all the files in the expected format to the memory card? Yes

**tonyhax version**: Latest Stable version
**Installation method**: Using Memory Card Anihilation on PS2
**Entry point game**: None
**Console model**: SCPH-1001
**Integrity check**: Yes
**BIOS version**: 2.1
**Target game**: SLES-02532

**Bug explanation**:

The issue im having is when im trying to boot (original game) RE 3 Nemesis PAL on my NTSC console, I select PAL to NTSC, the game boots succesfuly but all i get its a black screen, no sound, no nothing... If i boot first Import Media Player Light 2.1 from tonyhax and then from IMPL 2.1 i boot the game as NTSC everything works just fine.

Also if i boot an bootleg game or backup in PAL to NTSC it goes just fine, but i want to use my original copy of RE 3 in spanish

**Comment by socram8888** [comment]
I don't understand. What do you mean by "select PAL to NTSC"? There's no such feature on tonyhax. You mean it automatically switches to NTSC?

**Comment by santiis2010** [comment]
> I don't understand. What do you mean by "select PAL to NTSC"? There's no such feature on tonyhax. You mean it automatically switches to NTSC?

Sorry,  i got confused cuz i also tryed freepsxboot, yes when im trying to boot the game it switch the PAL game to NTSC but i only see a black screen and nothing happens, the same with freepsxboot when i select pal to ntsc. it only works if i boot first IMPL 2.1 and then i boot the game as NTSC

**Comment by socram8888** [comment]
Would it be possible to try again with the latest v1.4.5? That should probably fix this issue.

**Comment by socram8888** [comment]
Closing. Feel free to reopen if the bug is still present.
