### ISSUE TITLE
Pocket MuuMuu Antipiracy screen

### ISSUE THREAD

**Issue by LuvPiano** [socram8888/tonyhax#103]
**tonyhax version**: 1.4.3
**Game name**: Pocket MuuMuu
**Game code**: SCPS-10076
**Executable hash**:
MD5: 84607a1febb810417e14d84024be1055
SHA-1: 143548b27fe15627481988feb0762f5399b336dc
**Triggered at**: immediately after loaded the disc, no logo appears
**Is the console chipped?**: yes
**Is it an original disc or a burned copy?**: original disc

**Comment by socram8888** [comment]
Fixed in current version. Coming tonyhax v1.4.4 will properly support this game.

**Comment by socram8888** [comment]
Available in [tonyhax v1.4.4](https://github.com/socram8888/tonyhax/releases/tag/v1.4.4)
