### ISSUE TITLE
Grind Session Antipiracy screen

### ISSUE THREAD

**Issue by MondoGecko** [socram8888/tonyhax#106]
**tonyhax version**: 1.4.3
**Game name**: Grind Session
**Game code**: SCUS-94568
**Executable hash**: MD5: 1b2ba55bc3eb92250b292a96ba93c656
**Triggered at**: Around 10 seconds after you start the first level in Competition mode, when a CDDA music track is supposed to begin playing
**Is the console chipped?**: No
**Is it an original disc or a burned copy?**: Burned copy
Also want to point out this is being played on an SCPH-30001 PS2, if it makes any difference.

**Comment by socram8888** [comment]
Fixed in 90c989d121aa3d106c4a6a90744b7106d0b1d6f9. Will be available in next tonyhax v1.4.4.
