### ISSUE TITLE
Wrong region detection on PS2 70002 PAL

### ISSUE THREAD

**Issue by ehs03y3ol** [socram8888/tonyhax#108]
**tonyhax version**: 1.4.3
**Installation method**: Copied files manually with LaunchELF.
**Entry point game**: Crash Bandicoot 3 PAL.
**Console model**: PS2 SCPH 70002 PAL
**Integrity check**: Yes
**BIOS version**: 5.0 06/15/04

**Bug explanation**:
Stops execution with "Unsupported region: Japan"

https://ibb.co/3p0GfzZ

**Comment by socram8888** [comment]
PS2 above SCPH35000 are not supported. They report themselves as Japanese units and lack the backdoor.

**Comment by ehs03y3ol** [comment]
That fine, but could you document this on https://orca.pet/tonyhax/? @socram8888

**Comment by socram8888** [comment]
![Screenshot_20210811-214623_Fennec](https://user-images.githubusercontent.com/515068/129093341-0cff0f51-d22c-4bc7-b602-5688b6b80812.jpg)
It is
