### ISSUE TITLE
Metal Gear Solid Integral Antipiracy

### ISSUE THREAD

**Issue by Kdenk** [socram8888/tonyhax#109]
**tonyhax version**: 1.4.3
**Game name**: Metal Gear Solid Integral
**Game code**: SLPM-86470
**Executable hash**: slpm_862.47
MD5: ce625f0ef4b5302fcf78be222c0b77ed
SHA1: e383db43b8a4fd58ff1cf41d46eab287de72fc36
SHA256: 4b8252b65953a02021486406cfcdca1c7670d1d1a8f3cf6e750ef6e360dc3a2f
**Triggered at**: after selecting game difficulty (new game)
**Is the console chipped?**: Yes
**Is it an original disc or a burned copy?**: Original

Testes on SCPH-9002 using FreePSXBoot loader (image for SCPH-9002 slot 2). Of course the same issue is present without tonyhax.

**Comment by socram8888** [comment]
Fixed in 3e140b8a9103897442c2adb4eb6dd27a84479344, will be in future tonyhax 1.4.4.

**Comment by socram8888** [comment]
Available in [tonyhax v1.4.4](https://github.com/socram8888/tonyhax/releases/tag/v1.4.4)
