### ISSUE TITLE
Crash bandicoot racing JAP software terminating screen

### ISSUE THREAD

**Issue by dorkdizzy** [socram8888/tonyhax#110]
**tonyhax version**: 1.4.3
**Game name**: Crash bandicoot racing
**Game code**: SCPS-10118
**Executable hash**: MD5: 8867111811c0f414cd1589bcd1905b3c
**Triggered at**: When the naughty dog box is about to burst
**Is the console chipped?**: No
**Is it an original disc or a burned copy?**: Burned copy

**Comment by socram8888** [comment]
Fixed in 21ca572f9df8f97dbb5404c2d8e09ecbbbc71bfd

**Comment by socram8888** [comment]
Available in [tonyhax v1.4.4](https://github.com/socram8888/tonyhax/releases/tag/v1.4.4)
