### ISSUE TITLE
SLPS-01516 game doesnt launch

### ISSUE THREAD

**Issue by GIKAS123** [socram8888/tonyhax#111]
Before opening this kind of issue, please ensure:
 - Are you using a compatible console version? Yes
 - Are you using CD-R media, and not CD-RW? Yes
 - Did you copy all the files in the expected format to the memory card? Yes

**tonyhax version**: 1.4.2b
**Installation method**: uLaunchELF from ps2
**Entry point game**: Crash Bandicoot 3 pal
**Console model**: SCPH-102
**Integrity check**: Succeded the integrity check but it doesnt get further than a black screen
**BIOS version**: 4.5 (2000-05-25)
**Target game**: SLPS-01516 (The Drug Store: Matsumoto Kiyoshi de Okaimono!)

**Bug explanation**:
After the tonyhax screen closes the screen remains black and nothing happens

**Comment by GIKAS123** [comment]
Nevermind... It turns out I used a ''bad'' iso (The MajorWave one). Fixed it by using the regular one.

**Comment by socram8888** [comment]
Glad to hear it's working
