### ISSUE TITLE
Kings field games stuck on ''starting''

### ISSUE THREAD

**Issue by GIKAS123** [socram8888/tonyhax#113]
Before opening this kind of issue, please ensure:

Are you using a compatible console version? Yes
Are you using CD-R media, and not CD-RW? Yes
Did you copy all the files in the expected format to the memory card? Yes
**tonyhax version**: 1.4.2b
**Installation method**: uLaunchELF from ps2
**Entry point game**: Crash Bandicoot 3 pal
**Console model**: SCPH-102
**Integrity check**: Succeded the integrity check (?)
**BIOS version**: 4.5 (2000-05-25)
**Target game**: SLUS-00158 (Kings Field (USA)) and SLPS-00017 (King's Field (Japan) (English Patched))

**Bug explanation**:
Both games freeze at tonyhax screen on ''starting'' after several burned cds and attempts. The japanese one also displays the message ''SYSTEM.CNF NOT FOUND'' but it goes on getting also stuck at ''starting''

**Comment by socram8888** [comment]
Is this working now?

**Comment by GIKAS123** [comment]
Oops sorry that was a mistake! However since I saw that a new version is out I tried it again but its still stuck on "starting"

**Comment by socram8888** [comment]
Okay, thanks for the clarification. Will have a look as soon as possible.

**Comment by socram8888** [comment]
Could you maybe try with this version: https://github.com/socram8888/tonyhax/issues/135#issuecomment-1338617010

**Comment by GIKAS123** [comment]
When I tried the game (at least the USA version because I have a lack of cds rn) with the tonyhax version you provided it worked flawlessly! Many thanks!

**Comment by socram8888** [comment]
Perfect! Thanks for the testing!
