### ISSUE TITLE
Installation Issue 

### ISSUE THREAD

**Issue by Zaku2-1** [socram8888/tonyhax#115]
Before opening this kind of issue, please ensure:
 - model :scph 101
 - 
 - Did you copy all the files in the expected format to the memory card? kinda

**tonyhax_scph-101_v4.5_slot2: 
**Installation method**:  ulaunchelf / annihilator 
**Entry point game**:  none
**Console model**: "SCPH-101
**Integrity check**: If it boots, does the built-in integrity check succeed?
**BIOS version**: If you can get to boot, which version of the BIOS does it report?
**Target game**: If the bug happens when launching a game, what's its name and game code? Example: "Spyro 3 (SCES-02835)"

**Bug explanation**:
I am trying to install tonyhax on my memory card using ulaunchelf /annihilator , i go threw the steps in annihilator and when I go to write the mc image it tells me "Selected File Already exist would you like to overwrite it"
I've tried 4 memory cards two being new . 
so i tried it on one to "overwrite it " and nothing happened when i tried to boot it on the psx .What am i doing wrong?

![20211008_203430](https://user-images.githubusercontent.com/92217905/136661054-fd30aa35-10d5-4f43-908f-b4fd47babe03.jpg)

**Comment by socram8888** [comment]
You are likely using the option to __read__ an image from the memory card, rather than the option to write to the memory card
