### ISSUE TITLE
Dualshock 2 bug

### ISSUE THREAD

**Issue by ghost** [socram8888/tonyhax#116]
Before opening this kind of issue, please ensure:
 - Are you using a compatible console version? Yes
 - Are you using CD-R media, and not CD-RW? Yes
 - Did you copy all the files in the expected format to the memory card? Yes

**tonyhax version**: 1.4.3
**Installation method**: Memory Card Annihilator 2.0 
**Entry point game**: FreePSXBoot
**Console model**: SCPH-102B
**Integrity check**: Not boot
**BIOS version**: v4.5E 05/25/00 
**Target game**: Not related to a game
**Bug explanation**:
i noticed something strange. Latest version of Tonyhax (1.4.3) in combination with FreePSXBoot on a PSOne SCPH-102B with a Dualshock 2 inserted the console freezes when clicking the memory card icon, all fine with an original Dualshock for PS1. With Unirom in combination with FreePSXBoot work fine with a Dualshock 2 too. I didn't test other console models or the Tonyhax with the Disc boot but this is the issue in my case.

**Comment by socram8888** [comment]
I am going to close this since it's literally the same setup I use (SCPH-102 with PS2 DS contorller) and it's working fine for me.
