### ISSUE TITLE
Um Jammer Lammy hangs on loading screens

### ISSUE THREAD

**Issue by CleoTheBirb** [socram8888/tonyhax#118]
Before opening this kind of issue, please ensure:
 - Are you using a compatible console version? yes
 - Are you using CD-R media, and not CD-RW? yes 
 - Did you copy all the files in the expected format to the memory card? yes

**tonyhax version**: 1.4.3
**Installation method**: I tranfered the files using ulaunchelf on PS2
**Entry point game**: Cool Boarders 4
**Console model**: SCPH-39001 (ps2)
**Integrity check**: Passes
**BIOS version**: 5.0
**Target game**: Um Jammer Lammy (SCUS-94448)

**Bug explanation**:
Game likes to lock up during loading screens, opening and closing disc tray seems to get it to load (even if the disc is taken out, the game still gets into the stage). Cannot seem to replicate this on a PS1 emulator.

**Comment by socram8888** [comment]
Could you please try with latest version? There's at least one report in #100 that it works as of latest version, using a PS2.

**Comment by socram8888** [comment]
No response and at least one report saying it works on PAL. Closing.

**Comment by alex-free** [comment]
> No response and at least one report saying it works on PAL. Closing.

Sounds like a disc read issue anyways.
