### ISSUE TITLE
Purple Text when using THPS 3 ntsc on a model 7501 ps1

### ISSUE THREAD

**Issue by datboi2008** [socram8888/tonyhax#119]
Before opening this kind of issue, please ensure:
 - Are you using a compatible console version?
 - Are you using CD-R media, and not CD-RW?
 - Did you copy all the files in the expected format to the memory card?

**tonyhax version**: Which version are you running? Please ensure you are running the latest stable, or a newer beta.
**Installation method**: How did you get tonyhax on the memory card?
**Entry point game**: Which game are you using to launch tonyhax?
**Console model**: Console product code, written on the bottom of the unit, such as "SCPH-7502"
**Integrity check**: If it boots, does the built-in integrity check succeed?
**BIOS version**: If you can get to boot, which version of the BIOS does it report?
**Target game**: If the bug happens when launching a game, what's its name and game code? Example: "Spyro 3 (SCES-02835)"

**Bug explanation**:
Please write a detailed explanation on which issue are you experiencing.
When loading tony hax from an offical memory card that had the save game copied onto it using UlaunchElf, It shows purple blocks in place of where text should be. I tried putting in my disk but it didn't load. IDK what could have cause this and ive been looking around for a while now. Im hoping someone can help

**Comment by socram8888** [comment]
Closed as there is not enough info.
