### ISSUE TITLE
Feature request: Increase size of the text

### ISSUE THREAD

**Issue by Dartomic** [socram8888/tonyhax#122]
I use the tiny PSOne monitor. It would be nice if the text font size were increased a little so that it all could be read on the little screen. Some of it is kind of too small for the pixels on the screen, and blurs in together so that the characters do not fully display. It is readable. This is only a feature request.

**Comment by Dartomic** [comment]
I didn't see how to label this issue as an enhancement. Sorry about that.

**Comment by socram8888** [comment]
No problem, I've changed it.

I am not sure if this would happen. The font is already readable on a normal sized CRT, and the other font the BIOS provides is almost four times the size, making it hard to read when the text is scrolling.
