### ISSUE TITLE
The Emperor's New Groove

### ISSUE THREAD

**Issue by TheCobraDeath** [socram8888/tonyhax#124]
**tonyhax version**: Which version are you running? Please ensure you are running the latest stable, or a newer beta. 1.4.3
**Game name**: The Emperor's New Groove
**Game code**: Game's serial number, eg "SCES-12345" SLUS-94571
**Executable hash**: SHA-1, SHA-256 or MD-5 of the game's main executable or the disc. This is important since there could be multiple revisions of the same game.
**Triggered at**: Please explain when is the screen shown, eg "after the Sony logo", or "after the first video" While loading to first level
**Is the console chipped?**: Yes or no. No
**Is it an original disc or a burned copy?**: Self-explaining. Burned

**Comment by socram8888** [comment]
Fixed in 86b34c71b667930c379c58c1777f4ce616197d9b. Will be available on next v1.4.4 release.

**Comment by socram8888** [comment]
Available in [tonyhax v1.4.4](https://github.com/socram8888/tonyhax/releases/tag/v1.4.4)
