### ISSUE TITLE
Read Error 9 on hacked games

### ISSUE THREAD

**Issue by ghost** [socram8888/tonyhax#125]
Before opening this kind of issue, please ensure:
 - Are you using a compatible console version?
 - Yes
 - Are you using CD-R media, and not CD-RW?
 - Yes
 - Did you copy all the files in the expected format to the memory card?
 - Yes

**tonyhax version**: 1.4.3
**Installation method**: wLaunchELF
**Entry point game**: TonyHawk Pro Skater 3
**Console model**: SCPH-102
**Integrity check**: Read Error 9
**BIOS version**: v4.5
**Target game**: Many

**Bug explanation**:
Trying to play PAL/NTSC selector patched or trained/cracked games in v1.4.3 returns a "Read Error 9" even though they worked perfectly in earlier versions.

Edit: i had to downgrade to version all the way to v1.1.2 even though i'm pretty sure the games worked fine before in v1.4.1, but they didn't when i tried again.

**Comment by socram8888** [comment]
Any game in particular I could test with? Also, do you happen to remember the last version it with with?Enviado desde mi Galaxy
-------- Mensaje original --------De: Gomam0n-afk ***@***.***> Fecha: 24/5/22  3:30  (GMT+01:00) Para: socram8888/tonyhax ***@***.***> Cc: Subscribed ***@***.***> Asunto: [socram8888/tonyhax] Read Error 9 on hacked games (Issue #125) 
Before opening this kind of issue, please ensure:

Are you using a compatible console version?
Yes
Are you using CD-R media, and not CD-RW?
Yes
Did you copy all the files in the expected format to the memory card?
Yes

tonyhax version: 1.4.3
Installation method: wLaunchELF
Entry point game: TonyHawk Pro Skater 3
Console model: SCPH-102
Integrity check: Read Error 9
BIOS version: v4.5
Target game: Many
Bug explanation:
Trying to play PAL/NTSC selector patched or trained/cracked games in v1.4.3 returns a "Read Error 9" even though they worked perfectly in earlier versions.

**Comment by Gomam0n-afk** [comment]
> Any game in particular I could test with? Also, do you happen to remember the last version it with with?

Here are the 2 games i tried which had the error.
Dino Crisis 2 (US Version) with B.A.D's PAL/NTSC, selector patch can be found at consolecopyworld.
Alien Trilogy P/N + Trainer by Paradox (hard to find, consolecopyworld's patch doesn't work on any ISO i've found.)
The patched version can be seen working here : https://youtu.be/TEobsLmi48s

I tested all the different versions 3 days ago, and they only worked on v1.1.2 on my console even though i remember at least v.1.3.5 working before, but i might be misremembering.

The only hacked game i managed to make work a few days ago was a russian copy of Tekken 2 + 3, which has been hacked too, but it has a custom made menu before launching the actual game.

**Comment by socram8888** [comment]
Closing since the author is gone and IMHO it's probably just a bad laser.
