### ISSUE TITLE
Disc not loading on slim PSone console

### ISSUE THREAD

**Issue by KPackratt2k** [socram8888/tonyhax#128]
Before opening this kind of issue, please ensure:
 - I am using a compatible console version.
 - I am using CD-R media, not CD-RW.
 - I bought the card from an eBay seller, so I would imagine they installed it correctly since it's working on another console.

TonyHax version 1.4.3
I bought the memory card from an eBay seller.
Tony Hawk's Pro Skater 2 (NTSC-U)
SCPH-9001 (works), and 2x SCPH-101 (not working).
The integrity check passes.
SCPH-9001: BIOS v4.1 12/16/97 A, 1st SCPH-101: BIOS v4.4 03/24/00 A, 2nd SCPH-101: BIOS v4.5 05/25/00 A

I have burnt the PS1 port of the 240p Test Suite using the image linked here:
[https://github.com/filipalac/240pTestSuite-PS1/issues/12](url)

Although it works perfectly on my fat PS1 (the SCPH-9001), it will not load on my two slim PSone consoles (SCPH-101). When attempting to load it on both slim consoles, I get the Disc error type D with either code 22 or code 12. What's even more annoying is I've managed to get it to work once without errors, but now it shows these errors every time I try to load it.

- I've tried cleaning the disc drive lens.
- I've also tried adjusting the laser potentiometer.
- I've burnt the disc at the slowest possible speed that my drive allows (10x).

The disc I used is a CMC Magnetics Maxell CD-R. I would try other brands of CD-R, but this is all I have. I've also heard that Verbatim discs are now CMC made, so I don't think those would help.

If anyone has any advise on getting this to work on a Slim PSone, I'd appreciate it. I initially thought Sony implemented stricter checks to make sure the slim consoles couldn't read burnt CDs, but considering other Slim PSone users have managed to get TonyHax to read discs just fine, I am baffled at this.

**Comment by socram8888** [comment]
According to https://github.com/grumpycoders/pcsx-redux/blob/0889ddf70e503751aff0b1a2873a07b88d68340b/src/mips/openbios/cdrom/helpers.c#L60, type D code 12 are thrown when a disc's sector cannot be read - ie it's probably the media's fault.

**Comment by KPackratt2k** [comment]
I pretty much forgot about this until you closed it. I was able to make a working copy of the disc (still using the same CMC Magnetics Maxell discs as before) by burning it again using an older CD burner - the 2005 vintage NEC DVD burner in my Windows XP computer. It turns out that the modern laptop form factor DVD burner in my Windows 7 computer wasn't cutting it in this case. I was told that laptop CD burners aren't 100% reliable for this situation, so I thought I'd try an older desktop form factor burner and sure enough, it works now. Now I can use 240p Test Suite on all of my PS1 consoles (fat and slim).

**Comment by alex-free** [comment]
CMC magnetics is complete garbage. I agree with socram8888. You want Verbatim datalifeplus from Mitsubishi (probably).
