### ISSUE TITLE
Tomba! 2 - The Evil Swine Return (USA) and Other Anti-Modchip Games Trigger Protection

### ISSUE THREAD

**Issue by AmuroRayMan** [socram8888/tonyhax#13]
On previous versions and the latest one (1.2.1) Tomba! 2 boots but triggers the anti-modchip protection. I'm not familiar with how the games detect modchips, I suppose since this is a softmod it has to be checking memory somewhere. 

On an older version I also had this happen to Aconcagua (Japan). I have been able to boot both games on a softmodded PS2 via the PSX Launch program, so I don't believe they also have libcrypt but I am not entirely sure.

As with the last issue I opened, let me know if my BIOS version would help. It is one of the small white psone models (US).

**Comment by socram8888** [comment]
libcrypt and antimodchip are two different beasts. The former requires properly writing the subchannel data to disc, which is doable. The later however checks for the presence and/or absence of the SCEx string, which is something that can't be replicated nor I can from tonyhax emulate.

tonyhax can't do anything regarding this, other than patching the game's executable on a case by case basis to disable it, something I am not against but would require considerable work.

**Comment by socram8888** [comment]
Well that was easy. Tomba 2! booting is supported in d3b4930a919f420945dc311ddcb79e31048af4f8.

tonyhax will automagically patch this game at boot so that the antipiracy check is completely skipped.

**Comment by AmuroRayMan** [comment]
Just wanted to say thanks for the quick fix and adding a framework in for other patches! I tested Tomba 2 a bit ago and it works great now.
