### ISSUE TITLE
Support for 512kb fake memory card

### ISSUE THREAD

**Issue by danielw86dev** [socram8888/tonyhax#131]
I confirm last builder (https://github.com/brad-lin/FreePSXBoot/commit/768069e77c5d8103db79e10a6426d7d71d14fbe4) work with fake 512kb, i build image with tonyhax and card is booting and working. Very thanks!

What im do:

Compile last builder
make image slot 2 with payload tonyhax 1.4.3
extract unirom 8.0.I, replace mcd for my BIOS 7502, biild ISO with mkpsxiso
boot with swap disk metod and install freepsxboot to menory card (fake 512kb)

**Comment by socram8888** [comment]
Waiting for https://github.com/brad-lin/FreePSXBoot/pull/101 to get approved.

**Comment by socram8888** [comment]
I've just changed the compilation to use my own fork with that fixed. Will be available in next v1.4.4 release.

**Comment by socram8888** [comment]
Available in [tonyhax v1.4.4](https://github.com/socram8888/tonyhax/releases/tag/v1.4.4)
