### ISSUE TITLE
Robbit Mon Dieu Anti-piracy

### ISSUE THREAD

**Issue by TheScapegoat** [socram8888/tonyhax#134]
**tonyhax version**: 1.4.3
**Game name**: Robbit mon Dieu (Japan)
**Game code**: SCPS-10103
**Executable hash**: I'm not familiar with PSX file formats, so I'm guessing PEX stands for Playstation Executable. I'm also not sure which file is the one you are looking for, so I will supply SHA-256 hashes of the two PEX files in the root of the disc:

startup.pex: a73c4cbf1ea3b44574acaadf550511c71330cf7cf2178ff3cf45005d5d800264
title.pex: 55f334cac8d480559d85d5cdcc1182ae01b5289bfe71f8b94647001815593b9e

**Triggered at**: Immediately after tonyhax screen changes to the game
**Is the console chipped?**: No, unmodified SCPH-101 with BIOS 4.5
**Is it an original disc or a burned copy?**: Burned

**Comment by socram8888** [comment]
Fixed in 89c5381be781729a896fc25c4a262fa455d6f3a2

**Comment by socram8888** [comment]
Available in [tonyhax v1.4.4](https://github.com/socram8888/tonyhax/releases/tag/v1.4.4)
