### ISSUE TITLE
Hello, Silent hill NTSC-J (code SLPM-86192)doesnt work on my europian ps1 pal with Tonyhax 1.4.3. Screen showing after first video, Console doesnt chipped. Original disc.

### ISSUE THREAD

**Issue by Newnoir** [socram8888/tonyhax#136]
**tonyhax version**: Which version are you running? Please ensure you are running the latest stable, or a newer beta.
**Game name**: Self-describing
**Game code**: Game's serial number, eg "SCES-12345"
**Executable hash**: SHA-1, SHA-256 or MD-5 of the game's main executable or the disc. This is important since there could be multiple revisions of the same game.
**Triggered at**: Please explain when is the screen shown, eg "after the Sony logo", or "after the first video"
**Is the console chipped?**: Yes or no.
**Is it an original disc or a burned copy?**: Self-explaining.

**Comment by socram8888** [comment]
Fixed in 3e140b8a9103897442c2adb4eb6dd27a84479344.

**Comment by Newnoir** [comment]
> Fixed in [3e140b8](https://github.com/socram8888/tonyhax/commit/3e140b8a9103897442c2adb4eb6dd27a84479344).

I don't understand what you sent me and how i can use it? If you said that it fixed so where i can find a new version of tonyhax to play in Silent Hill NTSC-J?

**Comment by socram8888** [comment]
I've not yet made any release with that patch, so you'd need to wait until I've polished everything enough to warrant a new release or compile it from scratch.

I'm gonna test some games with real hardware and will make a release after that.

**Comment by socram8888** [comment]
Available in [tonyhax v1.4.4](https://github.com/socram8888/tonyhax/releases/tag/v1.4.4)

**Comment by Newnoir** [comment]
thanks very much, super, it works
________________________________
От: Marcos Del Sol Vives ***@***.***>
Отправлено: 26 ноября 2022 г. 3:18
Кому: socram8888/tonyhax ***@***.***>
Копия: Newnoir ***@***.***>; Author ***@***.***>
Тема: Re: [socram8888/tonyhax] Hello, Silent hill NTSC-J (code SLPM-86192)doesnt work on my europian ps1 pal with Tonyhax 1.4.3. Screen showing after first video, Console doesnt chipped. Original disc. (Issue #136)


Available in tonyhax v1.4.4<https://github.com/socram8888/tonyhax/releases/tag/v1.4.4>
