### ISSUE TITLE
BIOS v2.0 (Extremely 'Early' SCPH-1001) Needs Different Offset For BIOS_DEVELOPER, bios_is_ps1 returns false

### ISSUE THREAD

**Issue by alex-free** [socram8888/tonyhax#139]
This was a fun one. I own an **extremely** early SCPH-1001 console manufactured in July of '95. It indeed has BIOS v2.0 A. My other October '95 SCPH-1001 console is BIOS v2.1 A for reference to how rare this actually is...

Right now, in your bios_is_ps1() function you are checking offset 0xBFC0012C for the 'CEX-' string. This string is actually at 0xBFC00129 in BIOS v2.0 and below. BIOS v1.0 and BIOS v1.1 where only found on the SCPH-1000 and 'early' SCPH-3000 Japanese consoles specifically though, so only BIOS v2.0 affects the original Tonyhax here. BIOS v2.0 is therefore treated as a PS2 in the current code which is obviously very bad and breaks many things now.

My fix is here https://github.com/alex-free/tonyhax/commit/4161869997b766eeab725d2dfef3433d27f8fe5b . Tested and working on real hardware, I was loosing my mind debugging this.

These images below show the different offset for BIOS v2.0 and below, and BIOS v2.1 and above in the DuckStation emulator CPU debugger:

![bios-2 0](https://user-images.githubusercontent.com/72545918/204454395-7b4f9459-a372-4631-9cbe-094e3c4431ed.png)

![bios-2 1](https://user-images.githubusercontent.com/72545918/204454398-3322aec3-758f-40f0-aa21-595fd5a2dd1f.png)

**Comment by socram8888** [comment]
Thanks for the tip! I'm thinking I might reverse the condition and instead check for the PS2 "PS compatible mode by M.T", which is consistent through all the PS2 consoles at the same offset. Or even easier, check if the first byte of the BIOS version is '5'.

**Comment by socram8888** [comment]
I've fixed it in commit 80f80e9d52bfd66423f9e8d1df15ef9d0fd3e2a8, by checking the console BIOS version which is consistent through all PS2 models. Also added a log before the BIOS version to see the detected console model.
