### ISSUE TITLE
Yugioh Forbidden Memories (USA) Anti Piracy Trigger

### ISSUE THREAD

**Issue by ShinoBin** [socram8888/tonyhax#14]
Using tonyhax 1.2.1 on a US SCPH-7501, the game SLUS_014.11 boots but then shows the software terminated message after the Konami logo. 

Video demonstration with output if necessary: https://youtu.be/QxadHbzvn4I

The only other game I've tried so far is Ape Escape (USA) which works fine.

**Comment by socram8888** [comment]
Should be fixed on: https://github.com/socram8888/tonyhax/commit/7f9e6429c997fa09d49ada9e89111cbf01bd613c

I don't have this game nor an American console to test, so if you can please do so. If you don't know how to compile the project please let me know and I'll upload a binary for you to test.

**Comment by ShinoBin** [comment]
A binary would be nice, I can test it at some point tomorrow.

**Comment by socram8888** [comment]
Alright, here it is. Let me know it it goes: [tonyhax-d8e759a3.zip](https://github.com/socram8888/tonyhax/files/6194041/tonyhax-d8e759a3.zip)

(Note to self: built from d8e759a3263b6b4f9a7632e58b8cbb79438510c5)

**Comment by qkwyx** [comment]
> 
> 
> Alright, here it is. Let me know it it goes: [tonyhax-d8e759a3.zip](https://github.com/socram8888/tonyhax/files/6194041/tonyhax-d8e759a3.zip)
> 
> (Note to self: built from [d8e759a](https://github.com/socram8888/tonyhax/commit/d8e759a3263b6b4f9a7632e58b8cbb79438510c5))

thanks. did test it on my scph-5501 thps2 and load yugioh forbidden memories usa and successfully bypass the antimod screen

**Comment by socram8888** [comment]
Perfect, good to know! Closing the issue.

**Comment by ShinoBin** [comment]
Fixed for me too, thanks.
