### ISSUE TITLE
Dragon Ball Z - Idainaru Dragon ball Densetsu does not load completely

### ISSUE THREAD

**Issue by dannmanahan** [socram8888/tonyhax#141]
Before opening this kind of issue, please ensure:
 - Are you using a compatible console version? Yes
 - Are you using CD-R media, and not CD-RW? No
 - Did you copy all the files in the expected format to the memory card? Yes

**tonyhax version**: Which version are you running? Please ensure you are running the latest stable, or a newer beta.
1.4.4
**Installation method**: How did you get tonyhax on the memory card?
PS2 LaunchELF
**Entry point game**: Which game are you using to launch tonyhax?
THPS2
**Console model**: Console product code, written on the bottom of the unit, such as "SCPH-7502"
SCPH-7001
**Integrity check**: If it boots, does the built-in integrity check succeed?
Yes
**BIOS version**: If you can get to boot, which version of the BIOS does it report?
BIOS: v4.1 12/16/97 A
**Target game**: If the bug happens when launching a game, what's its name and game code? Example: "Spyro 3 (SCES-02835)"
Dragon Ball Z - Idainaru Dragon ball Densetsu (SLPS-00355)
**Bug explanation**:
Game loads and plays FMV. Demo loads as well. However, when you press start on TITLE screen, game goes black and does not load menu select as it should.

**Comment by alex-free** [comment]
I took a look at this game, I see that sectors 13-16 are containing invalid EDC data. This may be the same type of protection as seen in the DDR games. Will confirm in a bit.

**Comment by alex-free** [comment]
Is reproducible with Tonyhax v1.4.4 Boot CD. It must be anti-piracy related because Tonyhax International works fine.

**Comment by socram8888** [comment]
@alex-free thanks for the testing, will have a look when I have some free time.

**Comment by socram8888** [comment]
@dannmanahan could you please test with the v1.4.5 version?

**Comment by dannmanahan** [comment]
Did not work. Here was the text from the newest update:

tonyhax v1.4.5

Integrity check passed
Console: PS1
BIOS: v2.1 07/17/95 A
Resetting drive
Unlocking drive
Drive region: American
Swap CD now
Initializing CD
Disc error type D code 12 (x11)
Init failed Reinitializing kernel
Swap CD now

**Comment by dannmanahan** [comment]
Test results were from with SCPH-1001 unit, which didn't work properly for both 1.4.4 as well. 
Tested using SCPH-7001 and is now working properly

**Comment by socram8888** [comment]
That error type D means "disc sector read error". Sounds like you have a dying laser pick up.
