### ISSUE TITLE
Dance Dance Revolution 5th Mix Infinite Loading Screens

### ISSUE THREAD

**Issue by SageSandwich** [socram8888/tonyhax#143]
Before opening this kind of issue, please ensure:
 - Are you using a compatible console version?
 - Are you using CD-R media, and not CD-RW?
 - Did you copy all the files in the expected format to the memory card?

**tonyhax version**: 1.44 / 1.45
**Installation method**: Transferred the files via uLaunchElf on PS2
**Entry point game**: Tony Hawks Pro Skater 2
**Console model**: SCPH-101
**Integrity check**: Passes
**BIOS version**: V4.4
**Target game**: Dance Dance Revolution 5th Mix (SLPM-86897)

**Bug explanation**:
The game boots fine all the way up to the main menu. From there, if I try to go into "Options" or "Training", the game will be stuck loading infinitely. I can confirm 100% that this happens with "Training" & "Options" however, I haven't tried the other options on the menu yet. I will get to that when I get a chance and add those details accordingly.

**Comment by alex-free** [comment]
This is probably also an EDC protected game. Can you try burning the CD image using either:
Alchol 120%
The latest dev branch of CDRDAO using the generic-mmc-raw and --swap arguments (more info here https://alex-free.github.io/cdrdao )

**Comment by SageSandwich** [comment]
> 

I'll try that, unfortunately, I don't have access to my PSOne or burner for a week or so, so I'll let you know how that goes.
Thank you for the suggestion.

**Comment by SageSandwich** [comment]
Burned a copy of the game using Alcohol 120% and that seems to have solved my issue.
The game no longer freezes.

**Comment by alex-free** [comment]
> Burned a copy of the game using Alcohol 120% and that seems to have solved my issue. The game no longer freezes.

Excellent, confirmed this in an EDC protected game.
