### ISSUE TITLE
Frozen on green loading screen

### ISSUE THREAD

**Issue by dougremer** [socram8888/tonyhax#147]
tonyhax v 1.4.5, scph-102 PAL installed via usb through ulaunchELF. tried on THPS2 and CB3, both to the same results. once i load tonyhax to stays on the blue screen for around 5 seconds then gets stuck on green until i shut the console off. music still plays on THPS but stops on crash once it gets to the green screen.

**Comment by socram8888** [comment]
If you are using the latest version of uLaunchELF, try with an older one. I bet that if you read back the tonyhax file from the memory card and compare it with the original save file it'd have gotten corrupted.
