### ISSUE TITLE
Struggling to get burnt games to load 

### ISSUE THREAD

**Issue by BoxIsMyNamee** [socram8888/tonyhax#148]
![7EC8DCA6-DEDA-46FE-9A83-FCD2FE80B00C](https://user-images.githubusercontent.com/125211580/235148189-086313f9-8553-4dff-b077-e51da4c89478.jpeg)
I’m getting a freeze right here. Wont do anything. I’m playing a burnt copy of Vib Ribbon (japanese).
I burn it via the Playstation preset on Alcohol 120%. Same CD-R’s I burn my Dreamcast games on. 

This is on my Phat PS2 390001, I have no idea what to do, but it looks like it’s so close to launching which is a bummer. Would love some help! 🙏🙌

**Comment by socram8888** [comment]
Please try with an original CD and see if tonyhax is able to boot them.
-------- Mensaje original --------De: BoxIsMyNamee ***@***.***> Fecha: 28/4/23  14:35  (GMT+01:00) Para: socram8888/tonyhax ***@***.***> Cc: Subscribed ***@***.***> Asunto: [socram8888/tonyhax] Struggling to get burnt games to load  (Issue #148) 

I’m getting a freeze right here. Wont do anything. I’m playing a burnt copy of Vib Ribbon (japanese).
I burn it via the Playstation preset on Alcohol 120%. Same CD-R’s I burn my Dreamcast games on.
This is on my Phat PS2 390001, I have no idea what to do, but it looks like it’s so close to launching which is a bummer. Would love some help! 🙏🙌

**Comment by BoxIsMyNamee** [comment]
> Please try with an original CD and see if tonyhax is able to boot them. -------- Mensaje original --------De: BoxIsMyNamee ***@***.***> Fecha: 28/4/23 14:35 (GMT+01:00) Para: socram8888/tonyhax ***@***.***> Cc: Subscribed ***@***.***> Asunto: [socram8888/tonyhax] Struggling to get burnt games to load (Issue #148) I’m getting a freeze right here. Wont do anything. I’m playing a burnt copy of Vib Ribbon (japanese). I burn it via the Playstation preset on Alcohol 120%. Same CD-R’s I burn my Dreamcast games on. This is on my Phat PS2 390001, I have no idea what to do, but it looks like it’s so close to launching which is a bummer. Would love some help! 🙏🙌 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Ok, I tried my copy of Ms. Pac Man Maze Madness and it did this screen. 
![4B4BCEB3-74C2-4081-B671-2C46F7DAB9F8](https://user-images.githubusercontent.com/125211580/235199815-3ed90dec-0f88-4e6c-aa7c-fcd6e7b2cf6a.jpeg)
and then booted the game correctly.

**Comment by BoxIsMyNamee** [comment]
> Please try with an original CD and see if tonyhax is able to boot them. -------- Mensaje original --------De: BoxIsMyNamee ***@***.***> Fecha: 28/4/23 14:35 (GMT+01:00) Para: socram8888/tonyhax ***@***.***> Cc: Subscribed ***@***.***> Asunto: [socram8888/tonyhax] Struggling to get burnt games to load (Issue #148) I’m getting a freeze right here. Wont do anything. I’m playing a burnt copy of Vib Ribbon (japanese). I burn it via the Playstation preset on Alcohol 120%. Same CD-R’s I burn my Dreamcast games on. This is on my Phat PS2 390001, I have no idea what to do, but it looks like it’s so close to launching which is a bummer. Would love some help! 🙏🙌 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

i burn it via imgburn for the first time just now. worked first time no problems. idk why your site says avoid imgburn…?

**Comment by socram8888** [comment]
Well, glad to hear it works for you.

The reason I mention that ImgBurn is not a good tool for burning software is that it fixes some intentional errors in the .bin files that trip [some protections](https://orca.pet/tonyhax/compatibility.html#edc-protection) in some games.

**Comment by BoxIsMyNamee** [comment]
I just don’t understand why shifting from alcohol to imgburn would work.
I’d assume alcohol would just work consistently. very strange.
