### ISSUE TITLE
Disney Tarzan USA v1.1 - Loading Executable failed

### ISSUE THREAD

**Issue by djzeit** [socram8888/tonyhax#15]
Stuck on the loading executable. It wont start.

**Comment by socram8888** [comment]
I thought SYSTEM.CNF files were automatically generated and would always follow the same format. But it looks like they were manually crafted and some contain errors and extraneous characters.

Disney Tarzan seems to have a trailing tab which I thought weren't allowed as everything else had been spaces, and this was getting sucked as part of the executable name.

![imagen](https://user-images.githubusercontent.com/515068/112295363-be8a2780-8c8b-11eb-8800-aedfe47360e6.png)

Fixed in 0c80f609cf6faa55cd3ffb3d3294fe64708ac66e.

**Comment by djzeit** [comment]
Perdon por la molestia soy nuevo ah esto del hacking pero entonces como es que lo arreglo? Gracias! Por cierto la version Japonesa del juego carga bien como si nada.

**Comment by djzeit** [comment]
Im sorry im new to the scene, how would I fix it? Thank you, Also the japanese version loaded up no problem

**Comment by socram8888** [comment]
Tienes tres opciones:
 * Esperar a que saque la v1.2.2 estable
 * Bajarte alguna de las versiones de prueba que he compilado despues (por ejemplo https://github.com/socram8888/tonyhax/files/6196934/tonyhax-commit-f3f2d72b.zip)
 * Compilarlo tú mismo

**Comment by djzeit** [comment]
Primero que nada muchisimas gracias por todo esto es excelente trabajo. 🙂 Y segundo esperare la nueva release con mejor compabilidad. Por cierto no se si sirva de mucho pero la version japonesa cargo sin problema. Gracias amigo.
________________________________

**Comment by socram8888** [comment]
Sí, supongo que la japonesa tendrá un SYSTEM.CNF formado como el resto de juegos. Este tenía un tabulador al final que mi código no entendia como espacio, sino como un caracter más del nombre del ejecutable, así que cuando intentaba cargarlo pues el sistema operativo le decía que, con razón, el fichero no existía.

**Comment by djzeit** [comment]
A ok ya estoy enpesando a entender muchas gracias. Todo esto de coding se me hace muy interesante. Sabes de algun libro oh algo donde pueda
yo aprender mas? Espero el nuevo realese con el update muchas gracias!
________________________________

**Comment by socram8888** [comment]
Está difícil. Empecé hace bastante años con lenguajes que ahora mismo se considerarían obsoletos, así que no puedo recomendártelos. Igual échale un ojo a algún tutorial de Python o similar, que es bastante amigable, fácil de empezar pero aún así tiene bastante salida.

**Comment by djzeit** [comment]
Wow increible amigo. Me imagino que aprender un solo lenguage es dificil ya me imagino los recientes lenguajes de coding. Muchas gracias por la recomendaciones. Le echare un ojo. Espero con ansias el nuevo update de tonyhax gracias
________________________________
