### ISSUE TITLE
Rayman has memory card issues

### ISSUE THREAD

**Issue by flybot2010-lab** [socram8888/tonyhax#150]
Rayman has memory card issues on tonyhax,
First saying the card is unformatted, then after creating the save file the program can’t find the save and asks for the original memory card then locks up.

(Done on a PS1 and not a PS2)

**Comment by socram8888** [comment]
Please provide all information requested in the template for bug reports.

**Comment by alex-free** [comment]
My guess is anti-fpsxboot patch conflict

**Comment by alex-free** [comment]
What rayman game even is this bug for? I can't investigate anything without the proper info. Bump.

**Comment by socram8888** [comment]
Closed due to lack of information and response
