### ISSUE TITLE
Chrono Cross sometimes freezes after battle

### ISSUE THREAD

**Issue by Cintari-** [socram8888/tonyhax#156]
**tonyhax version**: 1.45
**Installation method**: Using "MemCard PRO for Playstation" with microSD card
**Entry point game**: N/A. FreePSXBoot is used
**Console model**: SCPH-7501
**Integrity check**:  Success
**BIOS version**: 4.1 12/16/97 A
**Target game**: Chrono Cross (SLUS-01041)

**Bug explanation**:
Occasionally after battles, after healing the party and collecting the spoils, the X button is not closing the battle and continuing the game. The battle screen remains stuck and the game is softlocked. The victory music continues to play. So far has only happened around 5 times after 9 hours of play, but annoying nonetheless.

**Comment by alex-free** [comment]
> **tonyhax version**: 1.45 **Installation method**: Using "MemCard PRO for Playstation" with microSD card **Entry point game**: N/A. FreePSXBoot is used **Console model**: SCPH-7501 **Integrity check**: Success **BIOS version**: 4.1 12/16/97 A **Target game**: Chrono Cross (SLUS-01041)
> 
> **Bug explanation**: Occasionally after battles, after healing the party and collecting the spoils, the X button is not closing the battle and continuing the game. The battle screen remains stuck and the game is softlocked. The victory music continues to play. So far has only happened around 5 times after 9 hours of play, but annoying nonetheless.

Does the disc drive sound like it is getting a disc read error (i.e. it spins up fast, gets loud, etc.)? 

Does this issue happen with Tonyhax International?

Does this issue happen if the FreePSXBoot cmemory card/memcard pro is removed after the Tonyhax loader is started?

Does this issue happen with other boot methods?

**Comment by Cintari-** [comment]
> Does the disc drive sound like it is getting a disc read error (i.e. it spins up fast, gets loud, etc.)? What CD-R media/burner/burn speed is being used?

The disc drive sounds like it is stopping and starting again, over and over. I'm using a standard CD-R disc, the game is burned using ImgBurn at default settings. The drive is an Asus DRW-24B1ST. I can tell you that I've burned two discs (the second having the "verified" hash from redump.org) and each has had the same issue. I've also played about a dozen other games with this method, and none have had any issues (or at least none that weren't resolved by Tonyhax updates).

> Does this issue happen with Tonyhax International?

I was not aware of Tonyhax international. In my current area of the game, I ran into this issue three times. After trying Tonyhax International, I got past it and did another 20 or so battles with no issue. It's hard to confidently say that it does _not_ happen with Tonyhax International, but it seems quite promising so far.

> Does this issue happen if the FreePSXBoot memory card/memcard pro is removed after the Tonyhax loader is started?

The Memcard Pro uses 8 virtual memory cards, specifically .mcd format files. The buttons on the device move between which memory card is currently loaded. FreePSXBoot is on card 8, sava data is on card 1. I always swap to card 1 immediately after Tonyhax loads so that data can be saved.

> Does this issue happen with other boot methods?

I was able to reproduce this issue pretty easily using the disc swap method, the entry point being Cool Boarders 4.

**Comment by alex-free** [comment]
"The disc drive sounds like it is stopping and starting again, over and over" really sounds like a disc read issue that can sporadically occur. What kind of CD-R is it? Can you try another brand of CD-R and or another burner?

Imgburn verification isn't really useful for figuring out how well the PSX can read the CD-R

**Comment by Cintari-** [comment]
The CD-R is a Verbatim brand 700MB 52x 80 min CD-R. I don't have any other CD-Rs or burners at the time being. But after playing another 5 hours on Tonyhax International, I still never ran into the issue again. I wound up ordering a copy of Chrono Cross for PSX, and for what it's worth I couldn't reproduce it on that either with Tonyhax 1.45 running. If no one else can reproduce this, it's probably on my end though.

**Comment by alex-free** [comment]
> The CD-R is a Verbatim brand 700MB 52x 80 min CD-R. I don't have any other CD-Rs or burners at the time being. But after playing another 5 hours on Tonyhax International, I still never ran into the issue again. I wound up ordering a copy of Chrono Cross for PSX, and for what it's worth I couldn't reproduce it on that either with Tonyhax 1.45 running. If no one else can reproduce this, it's probably on my end though.

Those are a known poor quality CD-R. Everything lines up, thanks for getting that info. https://alex-free.github.io/psx-cdr/#verbatim-80-minute . I recommend getting CMC Pro discs https://alex-free.github.io/psx-cdr/#cmc-pro-powered-by-taiyo-yuden-technology-80-minute
