### ISSUE TITLE
Jikkyou Powerful Pro Yakyuu '95 (Japan) (Rev 0) has no 'PS-X EXE' text in header

### ISSUE THREAD

**Issue by alex-free** [socram8888/tonyhax#162]
The game [Jikkyou Powerful Pro Yakyuu '95 (Japan) (Rev 0)](http://redump.org/disc/9552/l) does not have the 'PS-X EXE; text in it's header. This was fixed in Rev 1:
![Screenshot from 2024-09-07 18-14-57](https://github.com/user-attachments/assets/7c39b5a2-b5e9-4617-9248-9db9769c2779)

This causes Japan Rev 0 to not boot with the newest executable header code recently added.

Commenting it out works fine. Not sure if it's worth checking for now since at least one game doesn't have it.

    exe_header_t * exe_header = (exe_header_t *) data_buffer;
	if (strncmp(exe_header->signature, "PS-X EXE", 8)) {
		debug_write("Info: header has invalid signature");
		//return;
	}

**Comment by socram8888** [comment]
I'd like to still like to check for it, even if we just disable the return and inform the user. FileRead might return complete garbage as we've seen if the laser goes out of bounds, and this information could be pretty useful for debugging such conditions.

Maybe the check could be replaced to checking if the executable code and the initial PC is within the bounds of the console main RAM (or a mirror), and if the stack resides within main RAM or the "fast RAM". Will mean more LOC but should work with every single game out there.

**Comment by alex-free** [comment]
> I'd like to still like to check for it, even if we just disable the return and inform the user. FileRead might return complete garbage as we've seen if the laser goes out of bounds, and this information could be pretty useful for debugging such conditions.
> 
> 
> 
> Maybe the check could be replaced to checking if the executable code and the initial PC is within the bounds of the console main RAM (or a mirror), and if the stack resides within main RAM or the "fast RAM". Will mean more LOC but should work with every single game out there.

On the over-seek PS2 issue, if that happens it will never get to the code checking for this because it will be unable to open the PSX.EXE file. You can add code to Tonyhax that will guarantee that the over-seek PS2 issue while in the loader never happens and it can open the PSX.EXE.

An alternative would be to check for what Rev 0 has instead of PSX-EXE. Check both signatures.

From my research it looks like a lot of the PS-X EXE format isn't required, just from what we know
1) Certain SP values (kings field issue)
2) Size (kileak the blood issue)
3) Signature (this)

So I like your idea as well because it's actually 100% mandatory. Let me know your thoughts.

**Comment by socram8888** [comment]
Patched in https://github.com/socram8888/tonyhax/commit/c897f18dd5bc8430343686ff4f979678933fd279.

I've simplified the FileRead checks, since the functions will [always either fill the entire buffer or return -1](https://github.com/grumpycoders/pcsx-redux/blob/main/src/mips/openbios/cdrom/filesystem.c#L265-L285).

**Comment by socram8888** [comment]
FYI @alex-free you might want to cherry pick https://github.com/socram8888/tonyhax/commit/ace42f56d5094782fc69e2cc7a56d12d59a75189 since I did an oopsie while rewriting the debug_write calls.

**Comment by alex-free** [comment]
> FYI @alex-free you might want to cherry pick https://github.com/socram8888/tonyhax/commit/ace42f56d5094782fc69e2cc7a56d12d59a75189 since I did an oopsie while rewriting the debug_write calls.

Thanks for the heads up, went ahead and fixed it with your current commit.
