### ISSUE TITLE
DDR (Japan) CD-ERROR

### ISSUE THREAD

**Issue by Jaceideu** [socram8888/tonyhax#164]
Before opening this kind of issue, please ensure:
 - Are you using a compatible console version? Yes
 - Are you using CD-R media, and not CD-RW? Yes, using CD-R
 - Did you copy all the files in the expected format to the memory card? Not applicable

**tonyhax version**: v1.4.5
**Installation method**: I'm launching tony hax from a cd
**Entry point game**: Launching from cd with a modchip
**Console model**: SCPH-7502
**Integrity check**:  Succesfull
**BIOS version**: v4.1
**Target game**: DanceDance Revolution (SLPM-86222)
**Bug explanation**:

The game launches properly, tv emits loud static when on the difficulty select screen in arcade mode. After launching a song after the intro, it shows "cd error" and stops the game. Game burned on a cd using Alcohol 120% with the "Generic Protected CD" preset, also tried "Playstation" preset with the same result. Game worked fine on an emulator.
USA version of DDR works on console without any issues.

**Comment by DinsFire64** [comment]
You might be running into issues with EDC on this game specifically. Have you tried burning it using cdrdao 1.2.5 or higher in raw mode?

https://alex-free.github.io/psx-cdr/burning-with-cdrdao.html

Sorry I can't test this for you, I'm having trouble getting my ps2 laser's to even read my burnt copies right now.

Sources:
https://github.com/socram8888/tonyhax/issues/121
https://alex-free.github.io/tonyhax-international/anti-piracy-bypass.html#edc
https://orca.pet/tonyhax/compatibility.html#edc-protection

**Comment by DinsFire64** [comment]
Okay I actually got a good burn off a Sony DRU-820A at speed 8. It wasn't my playstation, this game is just difficult to burn properly...

With cdrdao burning with swap, I have working CD Audio in the game's arcade mode. No CD Error.

**Comment by socram8888** [comment]
Perfect, thanks @DinsFire64 !
