### ISSUE TITLE
Persona 2 Duology - FMV Crash

### ISSUE THREAD

**Issue by Incineroar** [socram8888/tonyhax#19]
First off, thanks for this amazing piece of software, it'll absolutely breathe in some life to my dust-collecting PS1. Anyway, wanted to try and offset some PS3 HDD space by playing some of the games I have there on my PS1, so I burned the Persona 2: Innocent Sin Genesis translation (Found here: http://www.romhacking.net/translations/1249/), as well as Persona 2: Eternal Punishment USA release (SLUS-01158), both ISOs were tested in an emulator as well to ensure they boot correctly and do as such, and the Innocent Sin translation works on a modified PS3 with ISO mounting tools.

So I tried Innocent Sin first on my PS1, and it seems that my burn is good, as the disc boots and shows both the patch introduction/credits screen, as well as the "if you bought this you've been scammed" screen, then hits a loading screen to load the Atlus logo FMV. Once the loading screen disappears and the game tries to play that FMV, the game seems to lock up on a black screen and becomes totally unresponsive. Deciding to then try Eternal Punishment, which _doesn't_ have those extra screens but instead just immediately shows the Atlus FMV, it just boots to a black screen and nothing more, indicating to me that whatever Atlus uses for playback of FMVs seems to be conflicting with something.

Tonyhax seems to run perfectly fine, it doesn't lock up while trying to load or anything, it's after the game itself has already started executing that things go wrong. The entrypoint I'm currently using is Brunswick Circuit Pro Bowling NTSC, so I'm not sure if that has any bearing on the game being able to load or not. I presume that fixing this FMV issue will fix both the NTSC-J releases of Innocent Sin (Tsumi) and Eternal Punishment (Batsu) as well as the USA release of Eternal Punishment, and this fan translation, and possibly other game developed by Atlus that use FMVs on the PS1, so this could fix a large number of titles if it's identified.

**Comment by socram8888** [comment]
That's interesting, as I've tried many different games with FMVs and never had any issue. I'll have a look.

**Comment by 17madman** [comment]
FYI I tried Persona 2 Eternal Punishment NTSC and it works fine, so it may not be Tonyhax, it might be a bad burn.

**Comment by Incineroar** [comment]
> FYI I tried Persona 2 Eternal Punishment NTSC and it works fine, so it may not be Tonyhax, it might be a bad burn.

That's definitely possible, although my modded PS3 can read it just fine for dumping. I've run out of CD-Rs though so I'll have to either find someone with a chipped system or find another way to verify my burned disc. This thought has crossed my mind though and I have been trying to verify my discs to make sure that's not an issue.

**Comment by socram8888** [comment]
For testing the CD I guess you could try the good old swap trick.

**Comment by Incineroar** [comment]
Well, after getting more CDs it seems whatever was burning them was messing around with the FMVs. Used Alcohol to burn this time around and it seems to work much better - the games actually do seem to work. Gonna close this since it seems to just be some bad burns.
