### ISSUE TITLE
Payload from bootmenu

### ISSUE THREAD

**Issue by gustavo-momente** [socram8888/tonyhax#21]
Not sure if this is the right place to ask. But would it be theoretically possible to launch the payload from there without using any game? Is there any know entry point in the bootmenu?

**Comment by krystalgamer** [comment]
In theory, yes it's possible. 

In pratice, the MMC manager doesn't seem to be that vulnerable. AcidSnake and I have poked around a bit but that's it.

**Comment by socram8888** [comment]
As he pointed out, it's highly unlikely. I fuzzes it a bit and found nothing interesting. Closing unless someone finds anything.

**Comment by gustavo-momente** [comment]
Now that [FreePSXBoot](https://github.com/brad-lin/FreePSXBoot) was released do you think this will be feasible?

**Comment by socram8888** [comment]
Surely. I've been working today on a tonyhax in EXE format to be loaded with FreePSXBoot. I wouldn't be able to test on real hardware, though.

**Comment by gustavo-momente** [comment]
Me too I only have 750X and 1003 consoles at hand at the moment.

**Comment by socram8888** [comment]
be430afc000c84a072fa9eec4cb2624e311f7d6c adds tonyhax as an executable. There's a bug right now with the builder (see https://github.com/brad-lin/FreePSXBoot/issues/5) so it's not really useable atm.

**Comment by gustavo-momente** [comment]
Soon everything will be working, thanks a lot for your contributions!

**Comment by socram8888** [comment]
v1.3.0 will have support for FreePSXBoot. Here's a version built from the current (131dac7fdfb53835f7f96d7b28ff4fd0be5adde8) tonyhax with FreePSXBoot images: [tonyhax-v1.3b.zip](https://github.com/socram8888/tonyhax/files/6302659/tonyhax-v1.3b.zip)
