### ISSUE TITLE
Ore no Ryouri stuck at piracy screen.

### ISSUE THREAD

**Issue by Tokugamer84** [socram8888/tonyhax#26]
Hello. So I’m using the Tony Hawk 3 Tonyhax files with a US PSone SCPH-101 with screen and I’m trying to use it to play Ore no Ryouri (Legit copy btw). Unfortunately, it was not able to get past the piracy screen. Normally when using the swap method with a PSXchange2 back in the day, I’d have to put in a Gameshark code to bypass this. Not sure if anything can be done like implementing cheat codes or disabling the “piracy  detection” on this; however, wanted to bring it to your attention. Thank you for your time.
![CC2990BD-B6AE-48A6-B91C-00D0A1E40385](https://user-images.githubusercontent.com/81402407/112577504-cac8ce80-8dca-11eb-8d61-f14f3c62fe73.jpeg)

**Comment by qkwyx** [comment]
What version of tonyhax are you using?

**Comment by Tokugamer84** [comment]
> What version of tonyhax are you using?

1.2.1

**Comment by qkwyx** [comment]
please try the beta build from @socram8888 https://orca.pet/shared/tonyhax-d1054546.zip

**Comment by socram8888** [comment]
No no, don't bother. These antipiracy games require per-game patching and this one isn't yet supported.

**Comment by qkwyx** [comment]
> 
> 
> No no, don't bother. These antipiracy games require per-game patching and this one isn't yet supported.

Oh i see now I know... nice to know, thanks.

**Comment by Tokugamer84** [comment]
Good to know, will wait for future support. Thanks. And thank you for making this hack. The inner child in me would have loved to have had this in my high school days. :D

**Comment by socram8888** [comment]
I've been looking at the disassembly but I can't find where is it getting triggered. Do you still have that cheat code you used?

**Comment by Tokugamer84** [comment]
> I've been looking at the disassembly but I can't find where is it getting triggered. Do you still have that cheat code you used?

Yep.

D0031C1A 1040
80031C1A 1000

**Comment by socram8888** [comment]
[tonyhax-c06dabf.zip](https://github.com/socram8888/tonyhax/files/6213633/tonyhax-c06dabf.zip)
This version should have it fixed. Please test it and let me know how it goes.

**Comment by Tokugamer84** [comment]
![8D16EC22-6155-448D-AEDA-761596227605](https://user-images.githubusercontent.com/81402407/112693793-9818e780-8e57-11eb-95cc-eca37779ac81.jpeg)

Awesome !! Works like a charm. Thank you !! :D

**Comment by socram8888** [comment]
Glad to hear it works now! One game less to be fixed.
