### ISSUE TITLE
Coolboarders 2

### ISSUE THREAD

**Issue by mailmartinviljoen** [socram8888/tonyhax#28]
I only have a working  coolboarders 2 disk  , my TR 2 disk has a small crack in the center and it would be super awesome if I could play a backup disk!

Any chance of creating a savegame for Coolboarders2  PAL ?

**Comment by socram8888** [comment]
Sorry but I am not interested in adding any more games myself. Until you can convince someone to add support for it and make a PR I'm closing this.
