### ISSUE TITLE
tetris With Cardcaptor Sakura: Eternal Heart japan wont play

### ISSUE THREAD

**Issue by dominater01** [socram8888/tonyhax#29]
the game has a antipiracy screen it shows a loading screen then bam call bla bla bla

https://i.ytimg.com/vi/TFbY0Nno9Jw/hqdefault.jpg

**Comment by socram8888** [comment]
blablabla fixed

**Comment by dominater01** [comment]
still having the issue after upgrading to v1.2.2

**Comment by Goldanas** [comment]
![IMG_20210408_154729](https://user-images.githubusercontent.com/67668858/114105652-fbf0d680-9881-11eb-8c73-98966c039f0b.jpg)
This is what I see on a PS2 30001R, running Tonyhax 1.2.3

**Comment by socram8888** [comment]
Yeah I saw that - given I didn't understand Japanese I though that was expected and I had to press some button or something, so without getting the black screen of death I assumed wrongly it was patched and working.

Will have a look again.

**Comment by socram8888** [comment]
[tonyhax-v1.3b.zip](https://github.com/socram8888/tonyhax/files/6320385/tonyhax-v1.3b.zip)

This version, compiled from 2ac8652c6ac00f6281605f3a67bc555668617296, should have it fixed.
