### ISSUE TITLE
Loading screen stall in Legend of Mana

### ISSUE THREAD

**Issue by Moukou** [socram8888/tonyhax#31]
**tonyhax version**: 
1.2.2
**Installation method**:
Ps2 ulaunchelf copy paste off usb into the ps1 memory card
**Entry point game**:
Cool Boarders 4
**Console model**:
SCPH-1001
SCPH-7501
SCPH-30001
**Integrity check**:
Integrity check passed on all three
**BIOS version**:
v2.2 12/04/95 A
v4.1 12/16/97 A
v5.0 12/28/00 A
**Target game**:
Legend of Mana (SLUS-10103)
**Bug explanation**:
1001: Infinite loading after loading a save (Very likely a bad lens though, it stalled on PlayStation splash for all three discs a lot)
7501: Infinite loading screen entering the city of Domina
30001: Same as 7501

Video of the 7501 and my raw save for easy reproduction
https://www.youtube.com/watch?v=At7Rx6E2yoM
[BASLUS-010131-1.zip](https://github.com/socram8888/tonyhax/files/6216362/BASLUS-010131-1.zip)

**Comment by socram8888** [comment]
![imagen](https://user-images.githubusercontent.com/515068/112803251-9cfdb700-9062-11eb-8233-61c183b0979a.png)
I cannot emulate this issue. Since this game has antipiracy (http://redump.org/disc/96/, see "EDC"), is it possible that your copy is missing subchannel data and thus having the protection triggered?

**Comment by Moukou** [comment]
I did use CloneCD to dump (ccd cue img sub) and burn with the custom profile like I did ages ago, similar to this old guide
https://www.ngemu.com/threads/how-to-make-a-perfect-backup-of-psx-games.34515
Dug into my old hdd and found the old 2004 dump (ccd cue img sub) and sadly doesn't get into Domina either

**Comment by RandomGamerRiven** [comment]
Just as a quick note I tried this on retail discs of both the NTSC/U and NTSC/J of Legend of Mana and both were working without issue, could enter, exit and move around the town of Domina and I also used the save you provided for the North American version. 

Version: Tonyhax 1.2.3b (Crash Bandicoot 2 PAL E)
Title: Legend of Mana (NTSC/U)
Product Number: SLPS-001013
Consoles tested on:
PS1 PAL SCPH-102 BIOS V4.5 05/25/00
PS2 PAL SCPH-39003 BIOS V5.0 03/19/02

No issue for me, I do want how many bad iso dumps there are out there on the net or if the game has additional protection that can detect it is not a original disc.

**Comment by socram8888** [comment]
@Moukou could you please compare the hash of your .img file against a known good? http://redump.org/disc/96/

Since this is booting fine on an emulator and real copy, I'm closing this as it's probably just a bad copy.

**Comment by Moukou** [comment]
@socram8888 Sadly the fresh dump matches the md5 and sha-1 http://puu.sh/Hu6EU/0a6b5f6938.png
I checked them and crc32 before. Matching it with the info on this romhack site so I could add this patch for emulation play, ideally we'd get the patch onto a burned cd to use the Pocketstation content on NTSC/U
https://www.romhacking.net/hacks/3680/

Gave a go with 1.2.3b from the other thread both this and my NTSC/J clone are tripping at that same loading screen for me which puts me at a loss if @RandomGamerRiven gets in just fine, so then is my burn method not right or maybe I need a different drive to burn with?

**Comment by hurda** [comment]
Reading the NGEMU-forum-post it says:
´Regenerate Data Sectors: Checked´
Wouldn't that "fix" the intentionally broken EDC-sectors?
Does that copy work in a modchipped PS1?

**Comment by Moukou** [comment]
Turned off the regenerate no luck still failed, gutted a drive from my ancient pc same settings I got into Domina! Thanks for the help now to try to patch it

**Comment by hurda** [comment]
@Moukou
Patch what with what, why?
What burners are you using?
Does CloneCD show these features to be supported for both drives?
https://i.imgur.com/Rpt6jA0.png

**Comment by Moukou** [comment]
@hurda 
Non-NTSC/J Legend of Mana has the option disabled to send a pet to a Pocketstation VMU showcased here https://www.youtube.com/watch?v=weHzPO4uPvw&t=63
This lets you play a minigame on the VMU rewarding you with items, some unobtainable without the VMU
This patch here adds the option back: https://www.romhacking.net/hacks/3680/
Using ignore checksum on xdelta lets the patch apply because the dump used was .img instead of .bin dump then burn like normal also ignoring checksum prompts. Putting it in the Playstation after running Tonyhax as my burned game entry it lets me use the Pocketstation option just like the Japanese version can

The working drive I pulled out of my old pc: HP DH-16AAL 8X DVD±RW DL SATA Drive w/LightScribe (Black)
Drive causing the error: Asus DVD-Writer Optical Drives DRW-24F1ST

The features are exactly the same on both drives just one works for this game and the other newer one doesn't with the exact same clone cd settings 
![image](https://user-images.githubusercontent.com/31049191/113520296-03517080-9560-11eb-94b2-92268d8f15c4.png)

**Comment by hurda** [comment]
@Moukou
Interesting and a bit weird.
You could try ripping those burned discs with CloneCD and check if they match with the source-files. Something has to be different.

Also: The patch is targeting a clean redump-rip, unchecking checksum-checks shouldn't be necessary.
The .img of your CCD-rip should have the same checksum (and size). If it doesn't, it's probably not a good rip.

**Comment by Moukou** [comment]
@hurda 
Weird the image I had tried using had the wrong MD5, maybe from a failed patch altering it. A fresh one did patched no problem that's great.
