### ISSUE TITLE
Add Generic Info to the README

### ISSUE THREAD

**Issue by nadrino** [socram8888/tonyhax#34]
As newbies like me just discovered the world of PS1 hacking, I think adding extra information on the README might be useful! I'm thinking especially at:

- Explicitly specifying CD-RW are not recognised by the PS1
- Should we burn games with or without Error Detection Checks? Or does tonyhax patch everything for us?

Cheers!

**Comment by socram8888** [comment]
Hello. Thanks for the suggestion. I've added this information to its Compatibility section: https://orca.pet/tonyhax/#compatibility
