### ISSUE TITLE
Incompatible games 

### ISSUE THREAD

**Issue by NotALuckyPey** [socram8888/tonyhax#35]
**tonyhax version**: 1.2.2
**Installation method**: USB->ULaunchELF->MC
**Entry point game**: THPS3/THPS4
**Console model**: SCPH-39008
**Integrity check**: Yes
**BIOS version**: v5.0 04/26/02 E
**Target game**: Ace Combat 2 (SLUS-00404), Nightmare Creatures (SLUS-00582), Test Drive 6 (SLUS-00839), Resident Evil 3 English (SLES-02529), Final Fantasy 7 Disc 1 English (SCES-00867), Final Fantasy Tactics (SCUS-94221), Pitfall 3D (SLUS-00254)

**Bug explanation**:
(Sry for engrish :/)
Hi, I tested some games on my PS2. These games don't work:
-Ace Combat 2 - freeze on "Starting". **Sometimes this issue happen on no$psx.**
-Test Drive 6 - black screen after FMV. **Same issue on no$psx.**
-Resident Evil 3 - freeze on "Starting" or "This game contains...". no$psx - only on "This game contains..." (Maybe libcrypt? I couldn't find any patch or patched version).
-Nightmare Creatures - black screen after tonyhax, works on no$psx.
-Final Fantasy 7 - black screen after intro (maybe bad laser). Works on no$psx.
-Final Fantasy Tactics - freeze on square logo. Not checked on no$psx, but there's MVG video https://youtu.be/8b5UX5xd-lE?t=269
Fun fact: NTSC-J version works just fine https://youtu.be/o6M_rp3HgLc?t=205
-Pitfall 3D - freeze on loading screen (maybe bad laser). Works on no$psx. 

Also, 1 bugged game:
Arcade's Greatest Hits: The Atari Collection 1 (SLUS-00399) - music from THPS continues to play in menu and FMV. After selecting games it stops.

If you want I can type all working games on my console. Anyway, thanks for this hack, I can finally complete PE2 and some TRPG's 👍

**Comment by RandomGamerRiven** [comment]
Just to add for me Final Fantasy Tactics [SCUS-94221] retail disc works fine for me on a PAL PS1 and PS2. The latter has a few graphics issues when running on PS2 for me on my unit. I used Tonyhax 1.2.2 with Crash Bandicoot 2

Consoles use:
PS1 SCPH-102 BIOS V4.5
PS2 SCPH-39003 BIOS V5.0 03/19/02

Final Fantasy Tactics is also known not to work on the SCPH-30001

**Comment by socram8888** [comment]
As explained on https://github.com/socram8888/tonyhax/issues/24#issuecomment-808786466, the PS2 is missing some initialization that could be the culprit and the reason some games work in the PS1 just fine but fail on the PS2.

**Comment by NE451** [comment]
tonyhax version: 1.2.3
Installation method: USB->ULaunchELF->MC
Entry point game: Brunswick Pro Bowling 1
Console model: SCPH-39004 (PS2)
Integrity check: Yes
BIOS version: v5.0 03/19/02 E

I tested some imported games I have and those are the results:
Resident Evil 2 NTSC-J (SLPS-01222) (original disc)
Dino Crisis NTSC-J (SLPS-02180) (original disc)
Dino Crisis PAL-I (SLES-02210) (backup done with SBI intact, I used CloneCD) 

All three of them hang on the violence warning screen.
I should try with a libcrypt-patched copy but I don't have any spare disc at the moment.

**Comment by socram8888** [comment]
@NE451 It's highly likely that given you are using a PS2, the problem you are facing is related to issue #24.

**Comment by NE451** [comment]
@socram8888 Yes, that's why I didn't posted a new thread.
I just wanted to point them out in case a talented debugger like you can find an update in the future!

Anyway, thanks for the work man

**Comment by socram8888** [comment]
The bug with THPS playing in the main menu of the Atari Greatest Hits collection should be solved in latest master. It disables the SPU (sound processing unit) as soon as it boots.

Will have a look at the two games that are crashing asap.

**Comment by socram8888** [comment]
[tonyhax-v1.3.5b.zip](https://github.com/socram8888/tonyhax/files/6519361/tonyhax-v1.3.5b.zip)

This version does a much more thorough reinitialization of the memory on the PS2. Could you please try it and report back?

**Comment by NE451** [comment]
Hi there! I've tried it, did a "fresh install" of TonyHax before everything else ( I was still on 1.2.3 ) and I'm using Brunswick 1 PAL. Game gets stuck at loading memory card, works fine if I use the stable release that you uploaded yesterday. 
I'm copy pasting below my setup, since nothing has changed.

Installation method: USB->ULaunchELF->MC
Entry point game: Brunswick Pro Bowling 1
Console model: SCPH-39004 (PS2)
BIOS version: v5.0 03/19/02 E


![photo_2021-05-21_10-51-41](https://user-images.githubusercontent.com/18534552/119110540-8d776a80-ba22-11eb-8b39-77376ba2ed25.jpg)

**Comment by socram8888** [comment]
@NE451 that is super odd. Coloring the screen happens right at the beginning, even before any system call is issued:

![imagen](https://user-images.githubusercontent.com/515068/119126293-615be980-ba22-11eb-9d85-515a4dcf3e3c.png)

Your issue indicates that something is screwing the entire payload.

**Comment by NE451** [comment]
I'm open for more testing!
I've also tried different memory cards but sadly I don't have a way to test with another game/entry.

**Comment by NotALuckyPey** [comment]
I checked 1.3.5b with THPS3:
AC2 - works fine.
Test Drive 6 - no changes, game doesn't work. Also music from THPS playing in first FMV.
Resident Evil 3 (License disc) - works and doesn't trigger LibCrypt... Burned disc doesn't work - SYSTEM.CNF not found.
Nightmare Creatures - works, but music from THPS playing in FMVs.
FF7 Disc 1 - works fine.
FFT - also works fine.
Pitfall 3D: burned disc - SYSTEM.CNF not found; factory-made pirated disc - stuck on loading screen.

In Arcade Collection sound bug is present: https://youtu.be/osjNllJO5gQ

**Comment by socram8888** [comment]
@NotALuckyPey can you try with this build of tonyhax v1.4b using commit cab2a9aaf8e6529c1d1ab47680949d2db84d8e65? [tonyhax-v1.4b.zip](https://github.com/socram8888/tonyhax/files/6538455/tonyhax-v1.4b.zip)

This new versions mutes every single audio channel before launching the game.

**Comment by socram8888** [comment]
Alright I've also tried Pitfall 3D and it works just fine, so I am gonna rule that out as a bad burn or weak laser. Test Drive 6 on the other hand does crash, so I'll be looking into it.

**Comment by socram8888** [comment]
TD6 has been fixed with latest commit. Closing as all the games are working for me.

**Comment by socram8888** [comment]
How did you get the PS2 BIOS working on no$psx? It does illegal memory access and dies on my PC

**Comment by NotALuckyPey** [comment]
I just dumped PSX part by [Bios Dumper](https://github.com/ShendoXT/biosdumper) on MCs and then merged into .BIN file. ePSXe dies with this BIOS, but no$psx works without problem (There's no SHELL, but anyway). I can upload this bios if you need.
![image](https://user-images.githubusercontent.com/56742724/119676171-54862e00-be46-11eb-9e1f-350386fc889e.png)

**Comment by socram8888** [comment]
Yeah that'd be extremely helpful. So far my development for the PS2 has been limited to looking on a disassembler and hoping it worked fine on a real machine haha.

**Comment by socram8888** [comment]
Alright, many thanks. Will try launching Pitfall 3D using the PS2 BIOS now. I used the SCPH-102 v4.4 BIOS (the same as my real console) and no$psx and it worked just fine when launched via tonyhax.
