### ISSUE TITLE
Legend of Mana (NTSC/J) [SLPS 02170] Retail disc triggers mod protection

### ISSUE THREAD

**Issue by RandomGamerRiven** [socram8888/tonyhax#36]
Version: Tonyhax 1.2.2 (Crash Bandicoot 2 PAL E)
Title: Legend of Mana (NTSC/J) 
Product Number: SLPS-02170
Boot name: SLPS_021. 70;1
Consoles tested on:
PS1 PAL SCPH-102 BIOS V4.5
PS2 PAL SCPH-39003 BIOS V5.0 03/19/02

Tested on latest version, but here's is a video of the issue of the boot on previous version information is the same. Unlike other games all the PS1 files are hidden even the System.cnf can't be seen on a PC without other software. 

Video: https://youtu.be/0aY2NHBGIug

Observed Result:
Game boots correctly with TonyHax, but triggers mod protection with a screen of Rabites appearing shortly after. Happy to regress issue myself when, bug marked as fixed. If you need any other information let me know.

**Comment by socram8888** [comment]
[tonyhax-v1.2.3b.zip](https://github.com/socram8888/tonyhax/files/6225142/tonyhax-v1.2.3b.zip)
Please try with the attached tonyhax.mcs/BESLEM-99999TONYHAX (the entry point save file stays the same, there's no need to replace it)

Compiled off commit https://github.com/socram8888/tonyhax/commit/aee07ce9f8cbb02675b4e4b71858635b3736178a

**Comment by RandomGamerRiven** [comment]
Confirmed it's working now, just tested on PS2 with Crash Bandicoot 2

Haven't played that far in, but the mod screen is no longer triggered, was able to get into game okay.

There was no sign of the Rabites, which only appear if the mod protection is triggered.

**Comment by socram8888** [comment]
This one was a pain in the ass to fix so I'm glad it was worth the effort. Closing.

**Comment by RandomGamerRiven** [comment]
By the way I should have said, if this board had a giant thumbs up button, I would have given you one for fixing this cheers.
