### ISSUE TITLE
Pop'n Music Series Anti-Piracy Screens

### ISSUE THREAD

**Issue by PARTYMANX** [socram8888/tonyhax#37]
**tonyhax version**: v1.2
**Game name**: Pop'n Music 2
**Game code**: SLPM-86294
**Console model**: SCPH-101
**Executable hash**: SHA-1 320B4F6E555D7F6B8D7B8A3EA2128B6146398D1F
**Triggered at**: after a black screen after the disc starts loading.

**tonyhax version**: v1.2
**Game name**: Pop'n Music 5
**Game code**: SLPM-86937
**Console model**: SCPH-101
**Executable hash**: SHA-1 CF663959CEA520E4DCF43260E38D725D5D8781E2
**Triggered at**: After the first loading screen

**tonyhax version**: v1.2
**Game name**: Pop'n Music 6
**Game code**: SLPM-87089
**Console model**: SCPH-101
**Executable hash**: SHA-1 BA7CAAF75CE244990D8CB1AB038F99EA7011C8D0
**Triggered at**: After the first loading screen

First game works fine, I don't have the two spin-offs to test with, I'd guess they have similar anti-piracy.  

I can't test the 3 and 4 append discs because 2 hits anti-piracy

I also tried Beatmania 6thMIX + Core Remix and hit the same anti-piracy screen as the latter two pop'ns, but I'll probably hold off on making a proper report until I can test the rest of the series.  It's probably safe to say the other Bemani (Beatmania, DanceDanceRevolution, Guitarfreaks) games will all need anti-piracy patches.

**Comment by socram8888** [comment]
Could you please double check the SHA1 sum for your Pop'n Music 2 game? I am getting `2ec68d51683085f78774fc42f07ab1a64cc4a1f` for a disc whose SHA1 sum is `ac4076d1258705a3ecb6e0f3c3da3aea3fc2799f` (which [matches the value at redump](http://redump.org/disc/9774/))

I've just added support for this game with commit 5f0a18170c57383765a4bfffdea86c7f74ad6989, but if your game's hash does not match it won't get patched.

**Comment by PARTYMANX** [comment]
whoops, you're right, I had accidentally taken system.cnf's sum for that one. 

yep, getting 2EC68D51683085F78774FC42F07AB1A64CC4A1F3 on the executable.  Thanks!

**Comment by socram8888** [comment]
[tonyhax-v1.3b.zip](https://github.com/socram8888/tonyhax/files/6314115/tonyhax-v1.3b.zip)

Here you go, fresh from the oven. Please update both the entry point (inside entry points) and the secondary (inside loader folder). Pop'n music 2 and 6 are already supported.

**Comment by Panikonn** [comment]
Coincidentally, I just tried to burn a copy of Beatmania 6thMIX + Core Remix and while it loads on my NTSC US 9001 PS1 with TonyHax thru THPS2 and FreePSXBoot, I get an anti piracy message after the "Please play away from tv and such" message. I did download the v1.3b package and the anti piracy messaged still occurred.

**Comment by socram8888** [comment]
@Panikonn that version isn't supported. It's got a game code SLPM-87012, which I had got no report yet.

Would you please open a new issue for that game so I can keep track of which games are missing antipiracy patches?

**Comment by Panikonn** [comment]
I will be sure to in a bit once I get the hash needed for the new topic. Thank you!

**Comment by socram8888** [comment]
Closing as all these games seem to work properly with the new v1.4 version.
