### ISSUE TITLE
Tonyhax fails to find the retail Chrono Cross NTSC/U boot file and can't launch game

### ISSUE THREAD

**Issue by RandomGamerRiven** [socram8888/tonyhax#38]
Version: Tonyhax 1.2.3b, also 1.2.2 (Crash Bandicoot 2 PAL E)
Title: Chrono Cross (NTSC/U)
Product Number: SLPS-01041
Boot name: unknown
Consoles tested on: 05/25/00
PS1 PAL SCPH-102 BIOS V4.5
PS2 PAL SCPH-39003 BIOS V5.0 03/19/02

Observed Result:
Tonyhax is unable to fine the boot files and can't launch the game, tested on an original retail copy of Chrono Cross.

![Chrono Cross TH60Hz NTSC Screenshot 2021-03-30 17-10-50](https://user-images.githubusercontent.com/81578209/113024660-eba07380-917e-11eb-8ee5-05b9afd51313.png)

**Comment by socram8888** [comment]
Also are you trying to boot the American or the Japanese one? The title says NTSC/U but SLPS is a Japanese product code

**Comment by RandomGamerRiven** [comment]
Should say the core file is named SLUS_10.41 on the disc only this and the System cnf can be seen in a PC, by default.
[CC.zip](https://github.com/socram8888/tonyhax/files/6230782/CC.zip)

**Comment by socram8888** [comment]
Alright, I made a mistake and forgot to use the "isspace" function on the string parsing, so it was once more chocking on a tab character.

This version should fix it: [tonyhax-v1.2.3b.zip](https://github.com/socram8888/tonyhax/files/6230860/tonyhax-v1.2.3b.zip) (compiled from https://github.com/socram8888/tonyhax/commit/1c94f46ee4b3c21927df91452e875784e2d1834b)

**Comment by RandomGamerRiven** [comment]
OK, I'll regress this for both discs and confirm if the fix works

**Comment by RandomGamerRiven** [comment]
Confirmed fixed, both discs successfully boot into game now. Also just to note starting a new game on disc 2 and swapping to disc 1 worked without issue.
