### ISSUE TITLE
Cool Borders 4 Greatest Hits fatal error (Red Screen) 

### ISSUE THREAD

**Issue by Defaultplayer001** [socram8888/tonyhax#43]
**1.2.2**: 
**Installed with PS2 using uLaunchELF 4.42d, 4.43 did not recognize PS1 memory card**
**Cool Borders 4**
**SCPH-101**

Says it loads the profile fine, but then displays red screen when selecting One Player. Tried multiple memory cards, and copying files over again to be safe.

**Comment by socram8888** [comment]
Closing since this game is known to work with that very console and game version: https://www.youtube.com/watch?v=T7vCeEqltF4

Did you install also the secondary payload, tonyhax.mcs/BESLEM-99999TONYHAX?

**Comment by Defaultplayer001** [comment]
Yes, of course.

Also I read the ReadMe multiple times and am well aware that this is listed as compatible, hence why I bought it on Ebay a week ago. 

TBH I find the immediate dismissal and assumption of ignorance kinda insulting.

**Comment by Defaultplayer001** [comment]
Accidently deleted it, so here's a paraphrase of a response I made a few minutes ago: 

Yes, I know, that's why I'm posting about it unexpectedly *not* working here, and also why I bought it a week ago on Ebay.

As I said I've tried copying over the files needed multiple times to be safe, and yes; I read the ReadMe.

To be honest I find the immediate dismissal and assumption of ignorance frustrating and confusing?

**Comment by socram8888** [comment]
Apologies. Thanks to previous experiences (see #10, #11, #16, and a myriad of other emails which I receive daily), I've grown up to immediately assume the user didn't bother to RTFM and preferred to bother me instead.

[tonyhax-cb4-full.zip](https://github.com/socram8888/tonyhax/files/6252361/tonyhax-cb4-full.zip)

Please try with the attached save files. These do a more thorough re-initialization of the memory cards before trying to load the SPL from them.

**Comment by Defaultplayer001** [comment]
I actually just tried yet again, this time with a different flash drive. 

It actually worked this time!

Seems it was the flash drive? Despite me having had no issues with it before. 

So TBF, you weren't wrong to suspect it being user error lol. Technically it *was* an issue on my end it seems. 

Sorry about that!  

Also TBF to the other users though, it could be a bit more straightforward?

IMHO considering how small the files are, I wouldn't worry about duplication and just make separate folders per specific game with all the files needed. 

Then you just need to need to simply tell users to copy everything from a specific folder, instead of the users having to sort through a large intimidating list of files themselves. 

Really impressed with this, can't thank you enough for it! 

Loading games like a dream, finally not dealing with any sound issues!

**Comment by hurda** [comment]
Just wanted to note that there was a bug in early versions of uLE 4.43 around 2016/2017 not working with original PS1-MCs. 4.42 didn't have that bug, it was introduced in one of those WIP-builds which came later, with 2TB-HD-support and whatnot.
https://github.com/ps2homebrew/wLaunchELF/issues/9
Latest version is from 2019, which can be found in the latest FMCB-Installer-archives as "BOOT.ELF".
