### ISSUE TITLE
Potential Gateway Suggestions (Crash Bash and Coolboarders 3) 

### ISSUE THREAD

**Issue by Audinosaur** [socram8888/tonyhax#45]
Hello, I am relatively new to the whole tonyhax scene and I have had the worst luck when getting my gateway setup. I have a copy of crash 2 but turns out the disc was completely dead (my fault for not testing a sketchy disc beforehand) I was looking through my library and noted I had some other similar but not matching games for ps1. 

I have no knowledge on how any of this works technically but was wondering if Coolboarders 3 or Crash bash would be potential gateway candidates due to being in the same line of already compatible titles. 

I have no idea how different each of these games would be from the other games in their series but I am hoping potential knowledge from the existing gateways could be applied

**EDIT:** Forgot to mention I am working off of NTSC games and an NTSC unmodded psone slim.

**Comment by looprewind** [comment]
@socram8888 I'm quite aware that you know that @ChampionLeake mentioned [over here](https://playstationdev.wiki/ps1devwiki/index.php?title=Vulnerabilities) the game Castlevania Chronicles. Could tonyhax be applied in this game? I'm a total noob to all these, it's just for curiosity and for learning! Thanks in advance

**Comment by socram8888** [comment]
@looprewind next time please use the search function: https://github.com/socram8888/tonyhax/issues/39

I am not myself interested at the moment in adding any more new games. Pull requests are welcome.

**Comment by looprewind** [comment]
my bad @socram8888! I've checked PR's before my comment, looks that someone needs a new pair of glasses 🤓
