### ISSUE TITLE
Resident Evil Survivor NTSC-U anti piracy screen

### ISSUE THREAD

**Issue by AbdomenFella** [socram8888/tonyhax#46]
tonyhax version 1.2,2
Resident Evil Survivor
SLUS-01087
Playstation 2 3900X
anti-piracy screen comes up

**Comment by Goldanas** [comment]
I might recommend this patch:
http://www.romhacking.net/hacks/4196/
It adds back in correct audio, light gun support (which if you're playing on real hardware and a CRT, you probably would want anyway), and also takes out the anti-piracy check.

I tested this out on my 30001R PS2, using Tonyhax and it works great.

**Comment by socram8888** [comment]
[tonyhax-v1.3b.zip](https://github.com/socram8888/tonyhax/files/6293605/tonyhax-v1.3b.zip)

Please try with this version. It should bypass the antimodchip check.
