### ISSUE TITLE
'crash2-us-tpl.mcs' file missing

### ISSUE THREAD

**Issue by salvadormrf** [socram8888/tonyhax#5]
I was trying to build the savefile for "Crash Bandicoot 2", but looks like this file is missing.
`crash2-us-tpl.mcs`

```
➜  tonyhax git:(master) ✗ make crash2-us.mcs
make: *** No rule to make target 'crash2-us-tpl.mcs', needed by 'crash2-us.mcs'.  Stop.
```

**Comment by socram8888** [comment]
I've been using git for years now, yet I still routinely forget "git commit -a" doesn't add new files. Solved in latest master.
