### ISSUE TITLE
Silent Hill

### ISSUE THREAD

**Issue by diamondhands97** [socram8888/tonyhax#53]
**tonyhax version**: 1.2.3
**Game name**: Silent Hill (original game ntsc-j)
**Game code**: SLPM-87029
**Console model**: SCPH-5552 PAL
**Executable hash**: Idk
**Triggered at**: the game starts, but is all grey and black, after few seconds I get the message I can't play it. The console has instaled one modchip to play burned games, on my PSOne I can play the game.

**Comment by socram8888** [comment]
The video being black and white is likely an issue with your television - in NTSC modes, PAL consoles output a slightly off colorburst frequency, which some TV sets can't properly decode: http://www.psxdev.net/forum/viewtopic.php?f=47&t=628

I will be looking at the antimodchip check though.

**Comment by socram8888** [comment]
I give up on this one. The game is made from a myriad of different shims much like Spyro 3, and it's highly unlikely this can be patched from within tonyhax with its super basic patching mechanism, so closing as won't fix.

**Comment by socram8888** [comment]
As a note, since v1.4 and thanks to the new approach used for patching antipiracy, this game should be also playable from tonyhax.
