### ISSUE TITLE
Freezing on green screen on Tony Hawk's Pro Skater 4 after demo mode has loaded

### ISSUE THREAD

**Issue by RAKtheUndead** [socram8888/tonyhax#54]
**tonyhax version**: 1.2.3
**Installation method**: Copied files using uLaunchELF 4.42d to memory card
**Entry point game**: Tony Hawk's Pro Skater 4 (PAL, SLES-03954)
**Console model**: SCPH-30003 R/SCPH-39003
**Integrity check**: Yes, when it starts properly
**BIOS version**: v5.0 12/28/00 E (SCPH-30003 R) / v5.0 03/19/02 E (SCPH-39003)
**Target game**: N/A

**Bug explanation**:
When using Tony Hawk's Pro Skater 4 (PAL) as an entry point for tonyhax, if the Create Skater option is selected after the game boots and the save loads, it enters properly into tonyhax. If the game reaches the Demo Mode due to inactivity, after it exits that mode, either through manual intervention (Start button) or by finishing the demo, selecting the Create Skater option results in the system freezing at the green screen. This may be a case of the story where a man goes to a doctor, saying, "It hurts when I do this" and the doctor replies, "Well, then, don't do that", but it makes me wonder if something would need to be done to reinitialise tonyhax after the game reaches the Demo Mode.

**Comment by socram8888** [comment]
I'm gonna be honest - I am gonna look into this just because I LOL'd.

I can't replicate it on the emulator, so it'll have to wait until I have access to the real console again, though.

**Comment by RAKtheUndead** [comment]
This could just be a PS2 issue as well; I took my SCPH-1002 (v2.2 E) and SCPH-102 (v4.5 E) out to try to replicate the issue (I haven't been using them with tonyhax generally because neither of them likes my CD-Rs) and while I can replicate the issue consistently on my PS2s, I couldn't replicate it at all on my original PlayStations.

**Comment by RAKtheUndead** [comment]
Decided to test this out with v1.3.5b because of the changes made for PS2 memory initialisation. Was able to successfully go through to tonyhax both after demo mode completed fully and after ending it in the middle by pressing Start when testing on SCPH-39003 with v5.0 BIOS. Will test later with SCPH-30003 R.

**Comment by RAKtheUndead** [comment]
Looks like it works with the SCPH-30003 R as well, consistently. I'm satisfied that this is solved now.

**Comment by socram8888** [comment]
Perfect, glad it's working now!
