### ISSUE TITLE
Net Yaroze DTL-H3000 (NTSC-J)

### ISSUE THREAD

**Issue by trinolmf** [socram8888/tonyhax#55]
Before opening this kind of issue, please ensure:
 - Are you using a compatible console version?
 - Are you using CD-R media, and not CD-RW?
 - Did you copy all the files in the expected format to the memory card?

**tonyhax version**: Which version are you running? Please ensure you are running the latest stable, or a newer beta.
**Installation method**: How did you get tonyhax on the memory card?
**Entry point game**: Which game are you using to launch tonyhax?
**Console model**: Console product code, written on the bottom of the unit, such as "SCPH-7502"
**Integrity check**: If it boots, does the built-in integrity check succeed?
**BIOS version**: If you can get to boot, which version of the BIOS does it report?
**Target game**: If the bug happens when launching a game, what's its name and game code? Example: "Spyro 3 (SCES-02835)"

**Bug explanation**:
Please write a detailed explanation on which issue are you experiencing.
tonyhax vesrion 1.2.2 & 1.2.3
Install method: dexdrive
Entry point game: thps2 de
Console: net yaroze dtlh-3000
Integrity check success
Bios v 2.2
Unsuported region

**Comment by socram8888** [comment]
That is expected. Japanese consoles are not supported.
