### ISSUE TITLE
Rainbow gradient overlay

### ISSUE THREAD

**Issue by trinolmf** [socram8888/tonyhax#57]
V.1.2.3
Dexdrive
Thps2 de
Scph1002 pal
Integrity passed
Bios 2.2
Nstc-u games
They load alright after a few try. But then some weird rainbow gradient overlays the game graphics, happenes in Metal Gear Solid ntsc-u and gran turismo 2 ntsc-u.
When loading metal gear solid pal version, then colors are fine

**Comment by socram8888** [comment]
Try on a different TV. That sounds like your TV isn't liking the signal from the console.

**Comment by socram8888** [comment]
I'm closing this since after investigating it's indeed a known design issue with the PS1: http://www.psxdev.net/forum/viewtopic.php?f=47&t=628
