### ISSUE TITLE
RedScreen issue Cool Boarders 4 PAL SCES02283

### ISSUE THREAD

**Issue by Antoniozip87** [socram8888/tonyhax#58]
Hi to all, Im using Tonyhax in a PS1 PAL SCPH-5502 and I get a redscreen when push one player in the Cool Boarders 4 SCES 02283. Can you please help me?
![16180647936395380592752756531274](https://user-images.githubusercontent.com/82275248/114273234-8a4b9080-9a19-11eb-822e-63b569bbcef1.jpg)
![16180648120189210743434536167947](https://user-images.githubusercontent.com/82275248/114273249-95062580-9a19-11eb-8723-100d34739891.jpg)
![16180648295012938444313719291357](https://user-images.githubusercontent.com/82275248/114273258-a0f1e780-9a19-11eb-9511-fe170fb5f49a.jpg)

**Comment by socram8888** [comment]
Please read the help page and what a red screen means
