### ISSUE TITLE
Einhänder (US) fails to pass first loading screen on PS2

### ISSUE THREAD

**Issue by RagnarokSam** [socram8888/tonyhax#61]
**tonyhax version**: v1.2.3
**Installation method**: PS2 > uLaunchELF > MC
**Entry point game**: THPS2 (US)
**Console model**: SCPH-39001 (PS2)
**Integrity check**: Passed
**BIOS version**: v5.0 02/07/02
**Target game**: Einhänder (SCUS-94243)

**Bug explanation**:
Game gets stuck on first loading screen (shows "Wait..." in lower-left corner) after showing "SCEA Presents" screen on PS2. Same game loads and plays flawlessly on PS1 model SCPH-7501 using same disc and memory card.

**Comment by socram8888** [comment]
This looks like the same issue as #24, but I might be wrong since this does actually successfully boots and then crashes, instead of crashing straight away.

**Comment by RagnarokSam** [comment]
Yeah, I was reading through #24 and thought it could be as well, but wasn't sure if I should add to that or make a new issue. Although I will say that the only other game I've tested on both is Clock Tower (US), and it runs fine on both. Not sure if that makes any difference or not though.

**Comment by socram8888** [comment]
[tonyhax-v1.3.5b.zip](https://github.com/socram8888/tonyhax/files/6519361/tonyhax-v1.3.5b.zip)

This version does a much more thorough reinitialization of the memory on the PS2. Could you please try it and report back?

**Comment by socram8888** [comment]
Closing as I am getting [a report on GbaTemp](https://gbatemp.net/threads/tonyhax-is-a-new-softmod-backup-loader-for-the-playstation-1.584717/page-18#post-9482157) that it is working fine now.
