### ISSUE TITLE
Integrity check fails

### ISSUE THREAD

**Issue by trinolmf** [socram8888/tonyhax#64]
Tonyhax 1.3
Memcardrex
Thps2 de
Scph1002
Check fails
Bios 2.2

**Comment by socram8888** [comment]
Please update the entry point. tonyhax 1.3 uses a different save for the entrypoint and using an older entry point save would make it load only the first 8192 bytes.

**Comment by trinolmf** [comment]
None of the files work for me. Neither those from the download zip nor the ones in the git folders(tpl files)

**Comment by socram8888** [comment]
Can you try reading back one of the saves you've written and attaching it here to see if there's anything corrupt in them?

**Comment by trinolmf** [comment]
They are just the same from the gitEm 18/04/2021 13:07, Marcos Del Sol Vives ***@***.***> escreveu:
Can you try reading back one of the saves you've written and attaching it here to see if there's anything corrupt in them?

**Comment by socram8888** [comment]
The files from the git (those named *-tpl.mcd) won't work since those are just skeleton files missing the executable code.

Please read the tonyhax file back and attach it here.

**Comment by trinolmf** [comment]
Did that, downloaded the new release 1.3 multiple times, same result. If i try to transfer the spl via dexdrive it gives me some error and aborts. With memcardrex transfer works. Sorry if i cant be of any helpEm 18/04/2021 16:08, Marcos Del Sol Vives ***@***.***> escreveu:
The files from the git (those named *-tpl.mcd) won't work since those are just skeleton files missing the executable code.
Please read the tonyhax file back and attach it here.
