### ISSUE TITLE
Resident Evil Director's Cut (& DualShock ver.)

### ISSUE THREAD

**Issue by EpsilonChurchRVB** [socram8888/tonyhax#66]
**tonyhax version**: 1.3.1
**Installation method**: via PS2 Free McBoot uLaunch 
**Entry point game**: Crash Bandicoot Warped (NTSC)
**Console model**: PS1 SCPH-9001
**Integrity check**: Yes
**BIOS version**: 4.1
**Target game**: Resident Evil Director's Cut (SLUS-00551) & Resident Evil Director's Cut Dual Shock Ver. (SLUS-00747)

**Bug explanation**:
Both games get stuck on "LOADING SYSTEM.CNF" after initializing CDs. 4 other games I've tested so far (RE2 DualShock Ver., RE3, Spyro the Dragon, and RE Survivor) don't have this problem and all run as well as they should.

**Comment by socram8888** [comment]
Hello! Thanks for the report. Are they burned discs or original retail ones?

**Comment by EpsilonChurchRVB** [comment]
> Hello! Thanks for the report. Are they burned discs or original retail ones?

No problem! They're burned on JVC Taiyo Yuden CD-Rs. Also forgot to mention it is an NTSC PS1 console.

**Comment by socram8888** [comment]
I'll try on my own console, but I **think** it could be just a bad burn. Getting stuck at that step means it can't even load the file's contents.

**Comment by EpsilonChurchRVB** [comment]
I burned them at the slowest my PC could possibly do (10x), which has worked for me so far up to that point in testing. I just burned other copies at MAX speed for both games and I'm still getting the same results. Pretty sure my games are ripped properly, unless my original copies were too scratched to read and export via imgburn, but I doubt it since they still are readable on both the PS1 itself and ePSXe emulator on PC.

**Comment by socram8888** [comment]
Could you please compare the checksum of your dumps against a known good copy? http://redump.org/disc/123/

Thanks!

**Comment by EpsilonChurchRVB** [comment]
I checked the checksum for both versions of the game via the Windows Powershell command and they all match both the MD5 and SHA1 hashes shown on the redump website. So I guess my ripped games being bad dumps is out of the question. Probably has something to do with my PS1 or tonyhax itself? I mean, the burned CDs work on ePSXe without any problem at all so idk.

**Comment by socram8888** [comment]
Alright thanks. I just wanted to rule out the obvious options.

Given that I understand you have the original discs too, could you try using then when tonyhax asks for a new CD?

**Comment by EpsilonChurchRVB** [comment]
I'll give it a try.

**Comment by EpsilonChurchRVB** [comment]
Huh... I should've tried the originals out first instead of wasting about 4-5 CDs lol. It still winds up getting stuck on the same thing for both versions of the game; "LOADING SYSTEM.CNF".

**Comment by EpsilonChurchRVB** [comment]
I'm not sure if it's an isolated case or not (probably something to do with my discs if it is indeed an isolated case), but if nothing can be done about it, I'm completely fine with it. I just didn't wanna wear out my originals on the PS1 as much as they already are.

**Comment by EpsilonChurchRVB** [comment]
So I may have found a workaround. A friend of mine just happened to have a retail NTSC Gameshark (v5.0) disc laying around in his old retro collection. They let me borrow it for the time being and got no problems with it running on Tonyhax. I loaded my slow-speed burned copy of RE Director's Cut (SLUS-00551) without any cheats and it worked like a charm! Same results happened with the other burned copy of the Dual Shock ver. (SLUS-00747) as soon as I finished testing the other one, from the intro itself, all the way to getting to the first save room.

I'm not sure if a burned Gameshark disc would work the same way, but I'm assuming it should be able to work regardless. I'm still not quite sure what's causing the "LOADING SYSTEM.CNF" stuck issues with my all of the RE1 discs I have, but at least this workaround is worthwhile.

**Comment by socram8888** [comment]
@EpsilonChurchRVB [tonyhax-v1.3.5b.zip](https://github.com/socram8888/tonyhax/files/6519361/tonyhax-v1.3.5b.zip)

This version does a much more thorough reinitialization of the memory on the PS2, and fixes a bug related to memory reinitialization on both the PS1 and the PS2. Could you please try it and report back?

**Comment by socram8888** [comment]
Just tried it myself and it works, so I'm closing this. Feel free to reopen if this bug still affects you.

**Comment by EpsilonChurchRVB** [comment]
> @EpsilonChurchRVB [tonyhax-v1.3.5b.zip](https://github.com/socram8888/tonyhax/files/6519361/tonyhax-v1.3.5b.zip)
> 
> This version does a much more thorough reinitialization of the memory on the PS2, and fixes a bug related to memory reinitialization on both the PS1 and the PS2. Could you please try it and report back?

Sorry, I didn't have time to both test it out and report back earlier today. Just tested the version you provided (v1.3.5b) and it works perfectly on the same PS1 with both games, including the backups and originals! Thank you so much!! I guess that said bug involving memory reinitialization was the root of the problem after all.
