### ISSUE TITLE
Jonah Lomu Rugby (SLES-00377) freezes on black screen after starting on PS2

### ISSUE THREAD

**Issue by RAKtheUndead** [socram8888/tonyhax#67]
**tonyhax version**: 1.3.1
**Installation method**: Copied across using wLaunchELF 4.43a to memory card
**Entry point game**: Tony Hawk's Pro Skater 4 (PAL, SLES-03954)
**Console model**: SCPH-39003
**Integrity check**: Yes
**BIOS version**: v5.0 03/19/02 E
**Target game**: Jonah Lomu Rugby (PAL, SLES-00377)

**Bug explanation**:
Game freezes on a black screen after displaying piracy notice. Issue occurs using original disc confirmed to be working correctly on same console when booting directly into disc. Suspecting a similar PS2-only issue to #24 as backup copies of the game load properly on an SCPH-102 (v4.5 E).

**Comment by socram8888** [comment]
[tonyhax-v1.3.5b.zip](https://github.com/socram8888/tonyhax/files/6519361/tonyhax-v1.3.5b.zip)

This version does a much more thorough reinitialization of the memory on the PS2. Could you please try it and report back?

**Comment by RAKtheUndead** [comment]
Tested using both original and backup copies; both working on SCPH-39003 with v5.0 BIOS. 

Also now loading fully: Final Fantasy Tactics (SCUS-94221) and Soul Blade (SLUS-00240), but both require PS1VModeNeg for proper timing/aspect ratio.

Still unable to load Kurushi (SCES-00866) - see opening post of #24.

**Comment by socram8888** [comment]
Perfect, glad this issue is fixed then!
