### ISSUE TITLE
1.3.1 Coolboarders EU entrypoint broken

### ISSUE THREAD

**Issue by faissaloo** [socram8888/tonyhax#68]
**tonyhax version**: 1.3.1
**Installation method**: wLaunchELF
**Entry point game**: Cool Boarders 4 (PAL-E)

**Bug explanation**:
This information was passed on to me, I don't know anything other than that the entrypoint fails

**Comment by socram8888** [comment]
Thanks for the report. Fixed with v1.3.2: https://github.com/socram8888/tonyhax/releases/tag/v1.3.2
