### ISSUE TITLE
Wrong game name in comment 

### ISSUE THREAD

**Issue by lzibeti** [socram8888/tonyhax#69]
Sorry for creating this Issue but checking this file I found that in this line it is saying "Silent Hill Survivor" instead of "Resident Evil Survivor".

Ps: I was looking at this file to check if it was possible to implement new games with Antipiracy 

https://github.com/socram8888/tonyhax/blob/e4644e34be33e7525200faca62d97f9e09acba2a/loader/patcher.c#L278

**Comment by socram8888** [comment]
Oops, thanks for the report. Fixed.

Adding support for new games it's possible but it's not an easy task, specially when they use weird dynamically-loaded modules.
