### ISSUE TITLE
Question: (possible?) Option to boot into Xploder/Xplorer/other Cheat Device menu

### ISSUE THREAD

**Issue by patrickvogt** [socram8888/tonyhax#7]
Just out of curiosity

Do you see a way (when an Xploder/Xplorer is attached), to unlock the cdrom drive and then boot into the xploder/xplorer menu to set some cheats (just the possbility, neglect the fact that you would need to detect the attached xploder/xplorer or would need to select this option "somehow" (controller or something else).

I checked Martins documentation about the xploder/xplorer boot process, but I really don't understand it.

Just ask, because how else should people enjoy "blonde Lara" with tonyhax (https://patrickvogt.net/blond_lara_blond.jpg) :-).

In the end there are other ways to use cheats with cdrs (without a modchip e.g. Unirom), I really just ask out of curiosity.

**Comment by socram8888** [comment]
I think if your hardware supports a physical cheat device you'd be much better using that with Unirom to unlock the drive and just skip the lengthy process of using tonyhax.
