### ISSUE TITLE
Tonyhax on FPSXB

### ISSUE THREAD

**Issue by Badore90** [socram8888/tonyhax#70]
Hi, sorry for my question being out of protocol, but I can't find any answer about this so I thought to directly ask you here.
 
Let me explain:

Tonyhax have some conveniences compared to FPSXB.

- No need to continuosly remove the MC (risking doing damage)
- The MC remains normally usable for other saves
- It's compatible with first Ps2 models (this is really great, being MechaPWN not compatible with those)

However if you use FPSXB as a tonyhax launcher, you loose those advantages.

Thus, being FPSXB already a perfectly working backup launcher and since using it I loose the tonyhax advantages, why should I boot tonyhax from FPSXB?
Something escapes me? Or it's just a feature for testing purposes (or also it could be useful in future when other features will be added)??

**Comment by socram8888** [comment]
Hello. Mainly because why not (it took like less than an hour), and secondary because it has a couple features Unirom can't do, such as patching the supported games that check for a modchip if you aren't running a stealth one, or have none installed at all.
