### ISSUE TITLE
Bio Hazard Gun Survivor NTSC-J anti piracy screen

### ISSUE THREAD

**Issue by lzibeti** [socram8888/tonyhax#72]
**tonyhax version**: 1.3.2

**Game name**: Bio Hazard Gun Survivor

**Game code**: SLPS-02553

**Console model**: PS1 FAT USA - SCPH-5501

**Executable hash**:  SLPS_025.53 - SHA1: BDBB116D0F5092ABAAF82142CF948786C85DAF28
Sorry but I didn't find the executable on the original CD 

**Triggered at**:  After the violence warning screen

**Comment by socram8888** [comment]
Thanks for the report. Fixed with da7726450e96b066615eba94adf62c38ec2cd918.
