### ISSUE TITLE
Dino Crisis NTSC-J anti piracy screen

### ISSUE THREAD

**Issue by lzibeti** [socram8888/tonyhax#73]
**tonyhax version**: 1.3.2

**Game name**: Dino Crisis

**Game code**: SLPS-02180

**Console model**: PS1 FAT USA - SCPH-5501

**Executable hash**:  SLPS_021.80 - SHA1: 610FEE67C86A920B457463EBFC831F48D9535BF5
Sorry but I didn't find the executable on the original CD 

**Triggered at**:  After the violence warning screen

**Comment by socram8888** [comment]
Thanks for the report. Fixed with d219a71fa589559bdac511385db37a0b622edb37.
