### ISSUE TITLE
Dino Crisis 2 NTSC-J anti piracy screen

### ISSUE THREAD

**Issue by lzibeti** [socram8888/tonyhax#74]
**tonyhax version**: 1.3.2

**Game name**: Dino Crisis 2

**Game code**: SLPM-86627

**Console model**: PS1 FAT USA - SCPH-5501

**Executable hash**:  SLPM_866.27 - SHA1: F224B2FD20A55D3F2B63EB0EACE2AD8703B379F1
Sorry but I didn't find the executable on the original CD 

**Triggered at**:  After the violence warning screen

**Comment by socram8888** [comment]
Just for the record: the reason this bug isn't being worked upon is that I am absolutely unable to source a clean disc image I can use on no$psx to find where the hell the antipiracy is.

**Comment by socram8888** [comment]
Closing as I've tried the USA version and that one passes, so I guess the v1.4 generic patch will work on the Japanese one. Feel free to reopen if it does not.
