### ISSUE TITLE
Dance Dance Revolution Games

### ISSUE THREAD

**Issue by happymealzero** [socram8888/tonyhax#76]
**tonyhax version**: Version 1.3.2
**Game name**: Dance Dance Revolution 2nd Remix, 3rd Mix, 4th Mix ,and 5th Mix
**Game code**: DDR 2nd Remix: SLPM-86252 , DDR 3rd Mix: SLPM-86503 , DDR 4th Mix: SLPM-86752, DDR 5th Mix: SLPM-86897
**Executable hash**: SHA-1, SHA-256 or MD-5 of the game's main executable. This is important since there could be multiple revisions of the same game. 
-DDR 2nd Remix MD5 : b950468a65e0d2d419862ece33160997
-DDR 3rd Mix MD5 : af1c53ec3a23600894017954a72ac015
-DDR 4th Mix MD5 : 175fe23fd016a3be5bac61c03ba04f15
-DDR 5th Mix MD5 : eb35cf0547e99859a1b253589ff76812
**Triggered at**: After "loading data on memory card" screen
**Is the console chipped?**: No

**Comment by socram8888** [comment]
Working on this. Will attempt to have this fixed for the next release (1.3.3)

**Comment by socram8888** [comment]
I've found the function to patch but I am stuck in a wall of Japanese text that I am unsure what it says:

![imagen](https://user-images.githubusercontent.com/515068/116799321-d6a16200-aae7-11eb-86d8-da47928cffec.png)

Any idea?

**Comment by happymealzero** [comment]
I used google translator app and here's what it says.
![Screenshot_20210501-200819_Translate](https://user-images.githubusercontent.com/83386382/116799827-05ecaa80-aab9-11eb-924c-004d6191178d.jpg)

**Comment by socram8888** [comment]
Thank you. Seems like it's totally unrelated.

I discovered the game seems to check its own integrity, so this might be trickier than I anticipated.

**Comment by socram8888** [comment]
Alright, so the problem with this one is that it seems to use a pretty clever way of preventing antipiracy from being defused.

Essentially the game seems to consist from several compressed/obfuscated? modules that are loaded one after the other. This is nothing out of the usual.

BUT what is out of the usual is that the code in one module depends on the code of the previous one - thus nuking the antipiracy call in the very first one trashes the code in the next one, and locks up with the screen you saw above.

This __might__ be patchable from within tonyhax if I reverse engineer the compression/obfuscation and alter the subsequent modules, but will not be included in the next release.

**Comment by socram8888** [comment]
[tonyhax-v1.4b.zip](https://github.com/socram8888/tonyhax/files/6529197/tonyhax-v1.4b.zip)

This is a bleeding edge version that uses a novel approach to patch the antipiracy. Could you please try it and report back?

**Comment by socram8888** [comment]
Tested on an emulator and it works fine for me, so I am closing this. Feel free to reopen if it does not for you.

**Comment by happymealzero** [comment]
I just tried them all right now and they work great. Thanks a lot.
