### ISSUE TITLE
Freeze when initializing cd

### ISSUE THREAD

**Issue by Ps2Fino** [socram8888/tonyhax#77]
Before opening this kind of issue, please ensure:
 - Are you using a compatible console version? Yes
 - Are you using CD-R media, and not CD-RW? Yes
 - Did you copy all the files in the expected format to the memory card? Yes

**tonyhax version**: v1.3.2
**Installation method**: uLaunchELF via Phat PS2
**Entry point game**: Crash Bandicoot 3 (SCES 01420)
**Console model**: "SCPH-102" (PS one)
**Integrity check**: Yes
**BIOS version**: v4.5 05/25/00 E
**Target game**: Parasite Eve 2 (SLES 02558) and Xenogears (SLUS 00664)

**Bug explanation**:
tonyhax freezes many times when initializing cd-r discs. I've tried this with Parasite Eve 2 (SLES 02558) and Xenogears (SLUS 00664). I use imgburn to burn bin + cue files created using imgburn from my original discs. Sometimes the discs will boot, but most of the time tonyhax sticks at the 'Initializing CD' step and just hangs indefinitely. I thought the issue was the laser but my PSOne boots the original copy of Crash Bandicoot 3 (SCES 01420) every time no problems. I've burned many different discs, and I've tried Verbatim and Phillips brands. Always CD-R. I also thought the issue may be my wireless controller (some kind of call to the controller port during bootup?) but my wired Dualshock 2 has the same issues. Please note that tonyhax itself boots every time no issues, it just freezes when initializing cds. This bug only happens sometimes e.g., as I'm writing this Parasite Eve 2 just booted up fine.

**Comment by socram8888** [comment]
Yeah that sounds like a dying CD laser. Reading an original disc is far easier for a disc unit than reading a burned one. The materials are totally different and tracking a ROM is easier.
