### ISSUE TITLE
Rockman 2 : Rockman Complete Works

### ISSUE THREAD

**Issue by bedwa** [socram8888/tonyhax#79]
**tonyhax version**: 
**Game name**: Rockman 2
**Game code**: SLPS_022.55
**Executable hash**: md5-4D3C76AC1881B22327F0DB718E3BC112
**Triggered at**: right after starting to load the game. No game screens or loading done.
**Is the console chipped?**: No

Side note, I would not be surprised if Rockman 1-6 had similar since they were a series re-released on PS in JP over the course of 5 months.

In addition, if you need a screen cap via obs of the process and what comes up, please let me know.

**Comment by socram8888** [comment]
Fixed with 1f28344f44827a51d7397ff195c5f60574409890.

If you can, please test it and report if it works for you: [tonyhax-v1.3.3b.zip](https://github.com/socram8888/tonyhax/files/6412224/tonyhax-v1.3.3b.zip)

**Comment by bedwa** [comment]
Works, will test Rockman 3 to see if it's same/similar and open a new report if not. TY as always for the hard work!

**Comment by socram8888** [comment]
Perfect, thanks for taking the time to test it.
