### ISSUE TITLE
Rockman 3 : Rockman Complete works

### ISSUE THREAD

**Issue by bedwa** [socram8888/tonyhax#80]
**tonyhax version**: 1.3.3b
**Game name**: Rockman 3
**Game code**: SLPS_022.62
**Executable hash**: MD-5 68D81B0B9B808FF0A4D10D5F52709422
**Triggered at**: Right after loading, goes straight to piracy screen
**Is the console chipped?**: No

**Comment by socram8888** [comment]
Thanks for the report. Fixed with d549d21efdc33cd8d625cb7d01f1dc95817e9a41.

Here's a test compilation, if you could have a look in real hardware: [tonyhax-v1.3.4b.zip](https://github.com/socram8888/tonyhax/files/6413659/tonyhax-v1.3.4b.zip)

**Comment by bedwa** [comment]
Works as expected, if needed, I can get the MD5's and game code for 1, 4-6 if needed to be preemptive on those if needed. I'm glad my hunch was correct on all of them being the same.
