### ISSUE TITLE
Gensei Kyokou Seirei Kidoudan: Elemental Gearbolt (NTSC-J) (SCPS 10038) Black Screen with Music

### ISSUE THREAD

**Issue by burntsiennna** [socram8888/tonyhax#85]
**tonyhax version**: v1.3.3
**Installation method**: USB -> Memory Card through uLaunchELF
**Entry point game**: Tony Hawk's Pro Skater 2 (NTSC-U) (SLUS-01066)
**Console model**: SCPH-30001
**Integrity check**: Passed
**BIOS version**: v5.0 7/27/00 A
**Target game**: Gensei Kyokou Seirei Kidoudan: Elemental Gearbolt (SCPS 10038)

**Bug explanation**:
After selecting "Create Skater" tonyhax successfully runs and prompts me to swap discs. Upon swapping discs, I am served with a black screen while Pro Skater 2's menu music plays. I couldn't find anything online about this game's anti-piracy or any special burning procedure, nor could I find anyone else reporting this specific issue, and the other game I tried (the NTSC-U version of Um Jammer Lammy) worked without a hitch.

**Comment by socram8888** [comment]
That is odd. Does the THPS2 music play while on the tonyhax menu?

**Comment by burntsiennna** [comment]
> That is odd. Does the THPS2 music play while on the tonyhax menu?

It does not. The music only starts after the disc has been swapped.

**Comment by socram8888** [comment]
Mmm alright. Will have a look then. Thanks

**Comment by RandomGamerRiven** [comment]
Gonna jump in here, haven't tested on the latest build but Seirei Kidoudan: Elemental Gearbolt did work on 1.3b as I tested my retail copy against it. My NTSC/J Japanese copy is SCPS 10038 and is a retail disc, I tested it successful using Crash Bandicoot 2 and Tonyhax. Sounds like this user is using a burn of the game, which may be incorrect. I do need to check my retail copy using the latest Tonyhax release to see it still works. Don't have Tony Hawk's Pro Skater 2 so can't test launch via that, but if burntsiennna has any other games that can launch Tonyhax I would test it with them. 

I would advise socram8888, you get people to list if they are using a burn of the game or a retail disc. As I suspect a lot of people are having burn problems and adding it as a bug with Tonyhax, when the fault is with the image or burn. Which means unneeded work for you. I will check this against the latest build myself just to be sure in the next few days that the retail disc is still working on the latest build release. If it isn't I will get back to you, but will be a few days before I can take a look at it, to confirm.

**Comment by socram8888** [comment]
Many thanks for your effort. I'm taking note and will add a question on the issue template so I know if the game is a burned or original copy.

My guessing this is just yet another incompatibility with the PS2 hardware, and it would work just fine on a PS1.

**Comment by socram8888** [comment]
Sorry accidentally closed it

**Comment by socram8888** [comment]
[tonyhax-v1.3.5b.zip](https://github.com/socram8888/tonyhax/files/6519361/tonyhax-v1.3.5b.zip)

This version does a much more thorough reinitialization of the memory on the PS2. Could you please try it and report back?

**Comment by burntsiennna** [comment]
> [tonyhax-v1.3.5b.zip](https://github.com/socram8888/tonyhax/files/6519361/tonyhax-v1.3.5b.zip)
> 
> This version does a much more thorough reinitialization of the memory on the PS2. Could you please try it and report back?

Seems like it works! Booted to title screen and into the first level without issue.

**Comment by socram8888** [comment]
Great! Glad the time spent decompiling the PS2 BIOS to understand the PS1 mode was worthwhile.
