### ISSUE TITLE
BeatMania 6th Mix + Core Remix Piracy Error

### ISSUE THREAD

**Issue by Panikonn** [socram8888/tonyhax#87]
tonyhax version: v1.3b
Game name: BeatMania 6th Mix + Core Remix
Game code: SLPM-87012
Console model: SCPH-9001
Is the console chipped?**: No
Triggered at: After safety warning screen game cuts to an english written antipiracy screen

Sorry for the lack of a hash, but I want to get the issue posted at least while I try to figure a way to find the executable hash. I am posting what tonyhax is saying right before loading the game up.

![20210516_214931](https://user-images.githubusercontent.com/82135283/118427208-4b50d080-b692-11eb-82d7-6dc6fd18d2d5.jpg)

**Comment by Panikonn** [comment]
While I am not sure if you need the hash directly from my file of the game, I do have the the MD5 hash from Redump.org as: 9ebfd4345f8a618669a1f744ae270f34

**Comment by socram8888** [comment]
The reason why I generally request it it's because many games have multiple revisions of the executable and bear the very same product code. Without it, it could happen (and has happened) that I patch the game and the reporter says it doesn't work, only to find later I had patched a different revision that the one he owned.

For this one there's only one revision so it's not really needed.

**Comment by Panikonn** [comment]
Thank you for clarifying that and for looking into this issue!

**Comment by socram8888** [comment]
[tonyhax-v1.3.5b.zip](https://github.com/socram8888/tonyhax/files/6510790/tonyhax-v1.3.5b.zip)

Please try with this version and let me know how it went. It should solve this bug.

**Comment by Panikonn** [comment]
![20210519_193350](https://user-images.githubusercontent.com/82135283/118901669-78db8b00-b8d9-11eb-835a-fb329ccf6446.jpg)
Success! Thank you again for your help! Just wondering, how hard is it to add in a antipiracy patch to the tonyhax code?

**Comment by socram8888** [comment]
Here's the list of patches. Each one has a tiny explanation on how they work: https://github.com/socram8888/tonyhax/blob/master/loader/patcher.c

Some are super easy and just need nuking (zeroing) a single call. Others are more convoluted and require patching considerable amount of code.

The biggest hurdle is that tonyhax can't patch anything other than the main executable, so those games that load the antipiracy from dynamically loaded modules are hard, if not impossible, to patch.
