### ISSUE TITLE
loading tonyhax from burned copy of THPS2

### ISSUE THREAD

**Issue by morzan007** [socram8888/tonyhax#93]
I get the blue screen of success. I see this https://drive.google.com/file/d/19JJ44eTuEXhntUph7Xbo4ABHa3DIZMsa/view?usp=sharing I loaded the burned copy using gameshark. Burned disc spins forever and I can't swap it for my import game (legit copy of Megaman 2)

Im on a psone. manufactured in 2000

**Comment by socram8888** [comment]
The bug template are there for a reason. If you are gonna use a burned disc, then use the boot CD version of tonyhax. Closing
