### ISSUE TITLE
Tonyhax update image.

### ISSUE THREAD

**Issue by MrSVCD** [socram8888/tonyhax#94]
I would like a install disc image for tonyhax and entry-points.

Could be combined with the boot disc and if you don't swap out the disc and press a button to bring up a menu to install the different things on the memory cards.

**Comment by socram8888** [comment]
![imagen](https://user-images.githubusercontent.com/515068/122685072-d9235c80-d1f8-11eb-95b1-6be3bc61c672.png)
Honestly that's something I planned but never got around implementing. Maybe some day.

**Comment by socram8888** [comment]
There's apparently an installer here so I'm closing this: http://www.psxdev.net/forum/viewtopic.php?f=66&t=3910
