### ISSUE TITLE
FreePSXBoot Slot 2 Update

### ISSUE THREAD

**Issue by rwebster85** [socram8888/tonyhax#98]
Hi mate. FreePSXBoot now has a Slot 2 version to save swapping out memory cards. Would it be possible to get a Tonyhax version of this new version at all please? :)

https://github.com/brad-lin/FreePSXBoot/issues/55

**Comment by socram8888** [comment]
Please try with this version: [tonyhax-v1.4.2b.zip](https://github.com/socram8888/tonyhax/files/6759604/tonyhax-v1.4.2b.zip)

**Comment by socram8888** [comment]
I'm closing this since I've tried on my SCPH-102 and seems to work. Feel free to reopen if you experience any issue.

**Comment by rwebster85** [comment]
Didn't realise there was a 1.4.2b mate, will give it a try :)

**Comment by socram8888** [comment]
There wasn't. I just compiled it haha
