### ISSUE TITLE
PS2 freezes at Checking game region

### ISSUE THREAD

**Issue by LuvPiano** [socram8888/tonyhax#99]
I use an SCPH-39001 with modbo 4.0 chip. I can use the burned tonyhax disc but when I swapped the CD, it stopped at Checking game region step and never goes on.

**Comment by socram8888** [comment]
Which version have you used?

**Comment by LuvPiano** [comment]
> Which version have you used?

I'm using v1.4.2

**Comment by socram8888** [comment]
Okay thanks for the report. This issue has been apparently introduced while attempting to fix issue #95 (pinging @DarthMotzkus which was the reporter of the issue).

That English translation uses a terrible hack - it essentially expects the sectors read from the CD to be at a predefined address, and they assumed (and I believed that) it was fixed through all PS1 and PS2 consoles.

However it is not - all PS1 consoles I've seen use 0xA000B070, but PS2 consoles use 0xA000A8D0 instead. Hence their approach is totally flawed, and attempting to make tonyhax compatible with it is what caused this breakage.

I will thus be rolling back this change and leaving it as it was before, and releasing a new v1.4.3 in a couple minutes with the old behaviour.

**Comment by socram8888** [comment]
Version v1.4.3 has been released, rolling back to the old behaviour and fixing this issue. Thanks for the report!

**Comment by DarthMotzkus** [comment]
Hi @socram8888, it breaks anything else than ps2 support? Can you send me the 1.4.2 final to save here. I will not use it on ps2. Still using the beta and i need mizzurna working... Thanks!

**Comment by socram8888** [comment]
@DarthMotzkus You should be able to use the v1.4.2 beta I sent you - there's no difference between that version and the final v1.4.2 I published other than a different version number: https://github.com/socram8888/tonyhax/issues/95#issuecomment-873667071
